## Загрузка, трансформация и обработка первичных данных

In [1]:
# импорт необходимых библиотек
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import kpss
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf
from pylab import rcParams
from IPython.display import display
import math
pd.set_option('display.max_columns', 130)

import warnings
from statsmodels.tools.sm_exceptions import InterpolationWarning
warnings.simplefilter("ignore", category=InterpolationWarning)
# pd.set_option('future.no_silent_downcasting', False)

#### Data preparation

In [2]:
# загрузка входных данных и сохранение в датасет
df = pd.read_excel("../input data/Данные-рус Обработанные (новые).xlsx")
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Показатель,Категория хозяйства,Регион,2015-01-01 00:00:00,2015-02-01 00:00:00,2015-03-01 00:00:00,2015-04-01 00:00:00,2015-05-01 00:00:00,2015-06-01 00:00:00,2015-07-01 00:00:00,2015-08-01 00:00:00,2015-09-01 00:00:00,2015-10-01 00:00:00,2015-11-01 00:00:00,2015-12-01 00:00:00,2016-01-01 00:00:00,2016-02-01 00:00:00,2016-03-01 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00,2018-03-01 00:00:00,2018-04-01 00:00:00,2018-05-01 00:00:00,2018-06-01 00:00:00,2018-07-01 00:00:00,2018-08-01 00:00:00,2018-09-01 00:00:00,2018-10-01 00:00:00,2018-11-01 00:00:00,2018-12-01 00:00:00,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00,2019-11-01 00:00:00,2019-12-01 00:00:00,2020-01-01 00:00:00,2020-02-01 00:00:00,2020-03-01 00:00:00,2020-04-01 00:00:00,2020-05-01 00:00:00,2020-06-01 00:00:00,2020-07-01 00:00:00,2020-08-01 00:00:00,2020-09-01 00:00:00,2020-10-01 00:00:00,2020-11-01 00:00:00,2020-12-01 00:00:00,2021-01-01 00:00:00,2021-02-01 00:00:00,2021-03-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-06-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-09-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00,2021-12-01 00:00:00,2022-01-01 00:00:00,2022-02-01 00:00:00,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,2023-01-01 00:00:00,2023-02-01 00:00:00,2023-03-01 00:00:00,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,2024-11-01 00:00:00,2024-12-01 00:00:00
2,КРС,Сельхозпредприятия,РЕСПУБЛИКА КАЗАХСТАН,3400.96,3685.9,4154.43,5203.94,5084.05,6718.83,4235.03,4014.95,4907.52,4274.75,3858.39,6477.35,3884.84,4146.9,4282.08,5408.9,4390.56,8005.48,5105.84,4700.12,5548.88,3958.09,6264.34,9196.32,3739.75,4951.17,6316.68,5751.36,5747.16,10114.01,5944.43,6768.61,5781.59,5885.5,7429.34,9411.91,5555.9,4586.48,7970.28,8130.34,8048.48,14491.87,7543.26,7396.97,9668.6,6730.17,7987.91,11121.61,5666.49,5917.68,8899.55,7784.95,9167.13,16299.73,7164.2,7341.17,10162.65,13532.56,11737.17,14948.7,7041.38,4341.74,10336.12,7419.05,10452.61,16413.66,7973.85,8901.52,10934.83,13130.82,12848.98,18882.81,8135.62,6432.18,9650.38,10482.45,11405.76,16121.49,9114.93,14885.29,13567.02,13473.97,12558.44,20382.82,6709.4,8554.71,12487.58,9184.25,7094.7,16471.11,6373.02,10145.08,8831.12,11123,8927.05,11379.06,7452.75,6836.85,8719.53,9925.26,7684.37,12218.39,6460.2,11289.58,15156.55,9790.74,9021.76,13193.63,6799.94,12303.66,9703.45,11165.56,8179.14,24407.52,9835.22,11955.41,16955.56,10638.42,9612.92,21521.5
3,КРС,Сельхозпредприятия,АКМОЛИНСКАЯ ОБЛАСТЬ,514.75,497.95,863.93,667.81,633.39,600.86,875.47,942.18,856.9,981.04,873.89,1390.18,736.62,845.64,774.36,618.97,701.72,796.48,914.5,736.52,897.89,912.46,867.99,1102.48,660.12,731.14,835,860.71,883.43,963.32,745.3,844.01,678,1025.12,1312.34,919.29,670.25,942.66,847.27,907.92,1002.24,911.62,873.09,1070.9,938.24,832.71,780.14,792.74,993.76,1044.12,1250.31,892.18,1441.82,1249.59,822.67,1007.64,1333,1160.5,1088.61,1164.95,782.49,829.6,1780.71,1077.39,1145.56,1100.69,898.78,829.67,930.63,1135.02,1025.99,1133.29,1141.02,957.47,1261.8,979.49,1029.19,864.06,1056.22,1019.37,1028.55,1254.05,1025.9,1062.94,537.96,1089,1631.34,1183.73,1118.31,1064.21,1240.11,1000.26,1269.72,1136.14,1230.95,1026.95,1294.11,936.76,1229.11,1048.76,1040.48,1181.82,869.84,993.64,938.85,1102.67,1001.63,1079.39,972.07,938.35,978.41,1071.35,1067.76,1119.61,898.07,1382,1133.36,1073.27,1118.19,1332.88
4,КРС,Сельхозпредприятия,АКТЮБИНСКАЯ ОБЛАСТЬ,554.41,504.35,493.56,445.51,585.79,316.47,469.49,303.09,685.51,600.85,603.26,700.48,477.84,221.08,265.59,328.03,384.03,555.07,615.9,619.33,770.79,302.27,1076.31,862.54,473.66,475.3,814.18,638.87,642.96,834.97,902.65,701.17,756.63,726.68,654.31,801.49,703.32,514.47,952.16,1018.39,968.68,845.85,758.18,931.47,1070.07,1278.41,1627.73,1714.64,704.51,899.66,1554.1,1351.44,1050.71,1485.45,814.13,1169.81,2388.34,1595.4,3809.76,3510.19,954.53,481.35,1111.55,1033.96,1939.87,2152.47,1578.87,1426.39,2620.87,2434.4,3247.3,3281.67,580.89,823.34,1221.21,1626.06,1920.41,2637.56,1620.81,2134.96,3425.67,3449.02,3751.75,3827.39,826.17,1132.81,1544.91,1885.46,698.01,4712.69,508.07,592.19,902.26,1479.36,1219.25,658.78,589.8,1275.24,1508.27,1380.18,842.24,3478.29,774.46,764.8,3003.94,1876.68,1547.77,607.03,609.08,873.05,1520.51,1747.09,915.8,1851.96,932.63,945.11,1142.92,1637.64,1180.54,1045.69

In [3]:
# удаление первого (пустого) ряда
df = df.drop(index=df.index[:1]).reset_index(drop=True)
df.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68,Unnamed: 69,Unnamed: 70,Unnamed: 71,Unnamed: 72,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101,Unnamed: 102,Unnamed: 103,Unnamed: 104,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120,Unnamed: 121,Unnamed: 122
0,Показатель,Категория хозяйства,Регион,2015-01-01 00:00:00,2015-02-01 00:00:00,2015-03-01 00:00:00,2015-04-01 00:00:00,2015-05-01 00:00:00,2015-06-01 00:00:00,2015-07-01 00:00:00,2015-08-01 00:00:00,2015-09-01 00:00:00,2015-10-01 00:00:00,2015-11-01 00:00:00,2015-12-01 00:00:00,2016-01-01 00:00:00,2016-02-01 00:00:00,2016-03-01 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00,2018-03-01 00:00:00,2018-04-01 00:00:00,2018-05-01 00:00:00,2018-06-01 00:00:00,2018-07-01 00:00:00,2018-08-01 00:00:00,2018-09-01 00:00:00,2018-10-01 00:00:00,2018-11-01 00:00:00,2018-12-01 00:00:00,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00,2019-11-01 00:00:00,2019-12-01 00:00:00,2020-01-01 00:00:00,2020-02-01 00:00:00,2020-03-01 00:00:00,2020-04-01 00:00:00,2020-05-01 00:00:00,2020-06-01 00:00:00,2020-07-01 00:00:00,2020-08-01 00:00:00,2020-09-01 00:00:00,2020-10-01 00:00:00,2020-11-01 00:00:00,2020-12-01 00:00:00,2021-01-01 00:00:00,2021-02-01 00:00:00,2021-03-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-06-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-09-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00,2021-12-01 00:00:00,2022-01-01 00:00:00,2022-02-01 00:00:00,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,2023-01-01 00:00:00,2023-02-01 00:00:00,2023-03-01 00:00:00,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,2024-11-01 00:00:00,2024-12-01 00:00:00
1,КРС,Сельхозпредприятия,РЕСПУБЛИКА КАЗАХСТАН,3400.96,3685.9,4154.43,5203.94,5084.05,6718.83,4235.03,4014.95,4907.52,4274.75,3858.39,6477.35,3884.84,4146.9,4282.08,5408.9,4390.56,8005.48,5105.84,4700.12,5548.88,3958.09,6264.34,9196.32,3739.75,4951.17,6316.68,5751.36,5747.16,10114.01,5944.43,6768.61,5781.59,5885.5,7429.34,9411.91,5555.9,4586.48,7970.28,8130.34,8048.48,14491.87,7543.26,7396.97,9668.6,6730.17,7987.91,11121.61,5666.49,5917.68,8899.55,7784.95,9167.13,16299.73,7164.2,7341.17,10162.65,13532.56,11737.17,14948.7,7041.38,4341.74,10336.12,7419.05,10452.61,16413.66,7973.85,8901.52,10934.83,13130.82,12848.98,18882.81,8135.62,6432.18,9650.38,10482.45,11405.76,16121.49,9114.93,14885.29,13567.02,13473.97,12558.44,20382.82,6709.4,8554.71,12487.58,9184.25,7094.7,16471.11,6373.02,10145.08,8831.12,11123,8927.05,11379.06,7452.75,6836.85,8719.53,9925.26,7684.37,12218.39,6460.2,11289.58,15156.55,9790.74,9021.76,13193.63,6799.94,12303.66,9703.45,11165.56,8179.14,24407.52,9835.22,11955.41,16955.56,10638.42,9612.92,21521.5
2,КРС,Сельхозпредприятия,АКМОЛИНСКАЯ ОБЛАСТЬ,514.75,497.95,863.93,667.81,633.39,600.86,875.47,942.18,856.9,981.04,873.89,1390.18,736.62,845.64,774.36,618.97,701.72,796.48,914.5,736.52,897.89,912.46,867.99,1102.48,660.12,731.14,835,860.71,883.43,963.32,745.3,844.01,678,1025.12,1312.34,919.29,670.25,942.66,847.27,907.92,1002.24,911.62,873.09,1070.9,938.24,832.71,780.14,792.74,993.76,1044.12,1250.31,892.18,1441.82,1249.59,822.67,1007.64,1333,1160.5,1088.61,1164.95,782.49,829.6,1780.71,1077.39,1145.56,1100.69,898.78,829.67,930.63,1135.02,1025.99,1133.29,1141.02,957.47,1261.8,979.49,1029.19,864.06,1056.22,1019.37,1028.55,1254.05,1025.9,1062.94,537.96,1089,1631.34,1183.73,1118.31,1064.21,1240.11,1000.26,1269.72,1136.14,1230.95,1026.95,1294.11,936.76,1229.11,1048.76,1040.48,1181.82,869.84,993.64,938.85,1102.67,1001.63,1079.39,972.07,938.35,978.41,1071.35,1067.76,1119.61,898.07,1382,1133.36,1073.27,1118.19,1332.88
3,КРС,Сельхозпредприятия,АКТЮБИНСКАЯ ОБЛАСТЬ,554.41,504.35,493.56,445.51,585.79,316.47,469.49,303.09,685.51,600.85,603.26,700.48,477.84,221.08,265.59,328.03,384.03,555.07,615.9,619.33,770.79,302.27,1076.31,862.54,473.66,475.3,814.18,638.87,642.96,834.97,902.65,701.17,756.63,726.68,654.31,801.49,703.32,514.47,952.16,1018.39,968.68,845.85,758.18,931.47,1070.07,1278.41,1627.73,1714.64,704.51,899.66,1554.1,1351.44,1050.71,1485.45,814.13,1169.81,2388.34,1595.4,3809.76,3510.19,954.53,481.35,1111.55,1033.96,1939.87,2152.47,1578.87,1426.39,2620.87,2434.4,3247.3,3281.67,580.89,823.34,1221.21,1626.06,1920.41,2637.56,1620.81,2134.96,3425.67,3449.02,3751.75,3827.39,826.17,1132.81,1544.91,1885.46,698.01,4712.69,508.07,592.19,902.26,1479.36,1219.25,658.78,589.8,1275.24,1508.27,1380.18,842.24,3478.29,774.46,764.8,3003.94,1876.68,1547.77,607.03,609.08,873.05,1520.51,1747.09,915.8,1851.96,932.63,945.11,1142.92,1637.64,1180.54,1045.69
4,КРС,Сельхозпредприятия,АЛМАТИНСКАЯ ОБЛАСТЬ,178.3,362.86,352.49,451.79,228.32,708.84,280.55,126.59,629.44,314.28,302.7,273.87,362.96,524.37,549.52,1221.29,663.04,1033.44,877.53,795.88,549.7,524.17,762.84,909.95,361.53,659.43,489.3,413.05,901.47,633.54,986.07,1245.53,678.11,462.36,1124.24,1042.7,626.23,691.69,900.64,546.92,753.49,1249.22,870.13,1085.25,767.07,833.67,621.67,1270.71,647.57,859.73,627.58,510.15,1060.85,748.1,795.62,713.09,917.57,2486.33,1047.68,1716.96,138.84,193.57,1915.13,318.06,1376.06,1100.94,732.62,403.93,1133.23,296.33,528.96,765.77,256.65,247.48,1642.59,204.04,1358.42,1168.3,299.38,1286.74,482.08,219.4,455.71,342.51,185.09,235.07,1692.44,276.34,475.5,1043.31,357.53,225.52,212.32,344.6,413.76,211.75,379.94,109.76,195.04,292.86,204.42,410.94,154.98,100.38,1354.58,189.29,152.57,186.92,141.97,214.08,1055.43,110.45,188.15,172.63,112.31,134.99,1212.02,260.02,129.38,159.66

In [4]:
# первый ряд как заголовки столбцов
df.columns = df.iloc[0] 
df = df[1:].reset_index(drop=True)
df.head(5)

,Показатель,Категория хозяйства,Регион,2015-01-01 00:00:00,2015-02-01 00:00:00,2015-03-01 00:00:00,2015-04-01 00:00:00,2015-05-01 00:00:00,2015-06-01 00:00:00,2015-07-01 00:00:00,2015-08-01 00:00:00,2015-09-01 00:00:00,2015-10-01 00:00:00,2015-11-01 00:00:00,2015-12-01 00:00:00,2016-01-01 00:00:00,2016-02-01 00:00:00,2016-03-01 00:00:00,2016-04-01 00:00:00,2016-05-01 00:00:00,2016-06-01 00:00:00,2016-07-01 00:00:00,2016-08-01 00:00:00,2016-09-01 00:00:00,2016-10-01 00:00:00,2016-11-01 00:00:00,2016-12-01 00:00:00,2017-01-01 00:00:00,2017-02-01 00:00:00,2017-03-01 00:00:00,2017-04-01 00:00:00,2017-05-01 00:00:00,2017-06-01 00:00:00,2017-07-01 00:00:00,2017-08-01 00:00:00,2017-09-01 00:00:00,2017-10-01 00:00:00,2017-11-01 00:00:00,2017-12-01 00:00:00,2018-01-01 00:00:00,2018-02-01 00:00:00,2018-03-01 00:00:00,2018-04-01 00:00:00,2018-05-01 00:00:00,2018-06-01 00:00:00,2018-07-01 00:00:00,2018-08-01 00:00:00,2018-09-01 00:00:00,2018-10-01 00:00:00,2018-11-01 00:00:00,2018-12-01 00:00:00,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00,2019-11-01 00:00:00,2019-12-01 00:00:00,2020-01-01 00:00:00,2020-02-01 00:00:00,2020-03-01 00:00:00,2020-04-01 00:00:00,2020-05-01 00:00:00,2020-06-01 00:00:00,2020-07-01 00:00:00,2020-08-01 00:00:00,2020-09-01 00:00:00,2020-10-01 00:00:00,2020-11-01 00:00:00,2020-12-01 00:00:00,2021-01-01 00:00:00,2021-02-01 00:00:00,2021-03-01 00:00:00,2021-04-01 00:00:00,2021-05-01 00:00:00,2021-06-01 00:00:00,2021-07-01 00:00:00,2021-08-01 00:00:00,2021-09-01 00:00:00,2021-10-01 00:00:00,2021-11-01 00:00:00,2021-12-01 00:00:00,2022-01-01 00:00:00,2022-02-01 00:00:00,2022-03-01 00:00:00,2022-04-01 00:00:00,2022-05-01 00:00:00,2022-06-01 00:00:00,2022-07-01 00:00:00,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,2023-01-01 00:00:00,2023-02-01 00:00:00,2023-03-01 00:00:00,2023-04-01 00:00:00,2023-05-01 00:00:00,2023-06-01 00:00:00,2023-07-01 00:00:00,2023-08-01 00:00:00,2023-09-01 00:00:00,2023-10-01 00:00:00,2023-11-01 00:00:00,2023-12-01 00:00:00,2024-01-01 00:00:00,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,2024-11-01 00:00:00,2024-12-01 00:00:00
0,КРС,Сельхозпредприятия,РЕСПУБЛИКА КАЗАХСТАН,3400.96,3685.9,4154.43,5203.94,5084.05,6718.83,4235.03,4014.95,4907.52,4274.75,3858.39,6477.35,3884.84,4146.9,4282.08,5408.9,4390.56,8005.48,5105.84,4700.12,5548.88,3958.09,6264.34,9196.32,3739.75,4951.17,6316.68,5751.36,5747.16,10114.01,5944.43,6768.61,5781.59,5885.5,7429.34,9411.91,5555.9,4586.48,7970.28,8130.34,8048.48,14491.87,7543.26,7396.97,9668.6,6730.17,7987.91,11121.61,5666.49,5917.68,8899.55,7784.95,9167.13,16299.73,7164.2,7341.17,10162.65,13532.56,11737.17,14948.7,7041.38,4341.74,10336.12,7419.05,10452.61,16413.66,7973.85,8901.52,10934.83,13130.82,12848.98,18882.81,8135.62,6432.18,9650.38,10482.45,11405.76,16121.49,9114.93,14885.29,13567.02,13473.97,12558.44,20382.82,6709.4,8554.71,12487.58,9184.25,7094.7,16471.11,6373.02,10145.08,8831.12,11123,8927.05,11379.06,7452.75,6836.85,8719.53,9925.26,7684.37,12218.39,6460.2,11289.58,15156.55,9790.74,9021.76,13193.63,6799.94,12303.66,9703.45,11165.56,8179.14,24407.52,9835.22,11955.41,16955.56,10638.42,9612.92,21521.5
1,КРС,Сельхозпредприятия,АКМОЛИНСКАЯ ОБЛАСТЬ,514.75,497.95,863.93,667.81,633.39,600.86,875.47,942.18,856.9,981.04,873.89,1390.18,736.62,845.64,774.36,618.97,701.72,796.48,914.5,736.52,897.89,912.46,867.99,1102.48,660.12,731.14,835,860.71,883.43,963.32,745.3,844.01,678,1025.12,1312.34,919.29,670.25,942.66,847.27,907.92,1002.24,911.62,873.09,1070.9,938.24,832.71,780.14,792.74,993.76,1044.12,1250.31,892.18,1441.82,1249.59,822.67,1007.64,1333,1160.5,1088.61,1164.95,782.49,829.6,1780.71,1077.39,1145.56,1100.69,898.78,829.67,930.63,1135.02,1025.99,1133.29,1141.02,957.47,1261.8,979.49,1029.19,864.06,1056.22,1019.37,1028.55,1254.05,1025.9,1062.94,537.96,1089,1631.34,1183.73,1118.31,1064.21,1240.11,1000.26,1269.72,1136.14,1230.95,1026.95,1294.11,936.76,1229.11,1048.76,1040.48,1181.82,869.84,993.64,938.85,1102.67,1001.63,1079.39,972.07,938.35,978.41,1071.35,1067.76,1119.61,898.07,1382,1133.36,1073.27,1118.19,1332.88
2,КРС,Сельхозпредприятия,АКТЮБИНСКАЯ ОБЛАСТЬ,554.41,504.35,493.56,445.51,585.79,316.47,469.49,303.09,685.51,600.85,603.26,700.48,477.84,221.08,265.59,328.03,384.03,555.07,615.9,619.33,770.79,302.27,1076.31,862.54,473.66,475.3,814.18,638.87,642.96,834.97,902.65,701.17,756.63,726.68,654.31,801.49,703.32,514.47,952.16,1018.39,968.68,845.85,758.18,931.47,1070.07,1278.41,1627.73,1714.64,704.51,899.66,1554.1,1351.44,1050.71,1485.45,814.13,1169.81,2388.34,1595.4,3809.76,3510.19,954.53,481.35,1111.55,1033.96,1939.87,2152.47,1578.87,1426.39,2620.87,2434.4,3247.3,3281.67,580.89,823.34,1221.21,1626.06,1920.41,2637.56,1620.81,2134.96,3425.67,3449.02,3751.75,3827.39,826.17,1132.81,1544.91,1885.46,698.01,4712.69,508.07,592.19,902.26,1479.36,1219.25,658.78,589.8,1275.24,1508.27,1380.18,842.24,3478.29,774.46,764.8,3003.94,1876.68,1547.77,607.03,609.08,873.05,1520.51,1747.09,915.8,1851.96,932.63,945.11,1142.92,1637.64,1180.54,1045.69
3,КРС,Сельхозпредприятия,АЛМАТИНСКАЯ ОБЛАСТЬ,178.3,362.86,352.49,451.79,228.32,708.84,280.55,126.59,629.44,314.28,302.7,273.87,362.96,524.37,549.52,1221.29,663.04,1033.44,877.53,795.88,549.7,524.17,762.84,909.95,361.53,659.43,489.3,413.05,901.47,633.54,986.07,1245.53,678.11,462.36,1124.24,1042.7,626.23,691.69,900.64,546.92,753.49,1249.22,870.13,1085.25,767.07,833.67,621.67,1270.71,647.57,859.73,627.58,510.15,1060.85,748.1,795.62,713.09,917.57,2486.33,1047.68,1716.96,138.84,193.57,1915.13,318.06,1376.06,1100.94,732.62,403.93,1133.23,296.33,528.96,765.77,256.65,247.48,1642.59,204.04,1358.42,1168.3,299.38,1286.74,482.08,219.4,455.71,342.51,185.09,235.07,1692.44,276.34,475.5,1043.31,357.53,225.52,212.32,344.6,413.76,211.75,379.94,109.76,195.04,292.86,204.42,410.94,154.98,100.38,1354.58,189.29,152.57,186.92,141.97,214.08,1055.43,110.45,188.15,172.63,112.31,134.99,1212.02,260.02,129.38,159.66
4,КРС,Сельхозпредприятия,АТЫРАУСКАЯ ОБЛАСТЬ,20.8,0.8,15.28,1.97,2.04,1.32,0.8,1.38,1,0.43,1.47,6.26,7.41,20.63,10.49,11.75,16.13,27.56,15.8,11.24,15.2,3.5,5.1,10.18,7.41,4.52,6.2,3.28,9.99,3.44,9.3,32.91,48.26,21.35,4.52,6.7,2.95,38.66,2.91,23.24,8.43,2.4,19.8,0.3,13.88,1.75,83.62,19.94,5.04,3.28,0.2,7.3,7.88,7.82,0.1,-,2.1,13.76,1.73,1.95,1.8,6.49,7.29,5.7,10.95,5.98,1.57,1.58,19.4,9.32,22.87,-,3.09,3.23,8.92,2.74,3.85,2.11,4.54,1.41,1.69,8.27,13.06,20.24,8.91,9.61,2.14,9.05,5.62,3.5,-,-,2.6,-,5.1,5.7,-,0.06,1.9,-,1.4,4.2,1.4,0.5,1.64,0.54,-,51.62,16.21,17.45,13.52,25.1,13.7,16.08,17.35,41.57,56.59,49.5,40.76,27.22

In [5]:
# трансформация столбцов с датами
df.columns = list(df.columns[:3]) + list(pd.to_datetime(df.columns[-120:]))
df = df.rename(columns={col: col.strftime("%Y-%m") for col in df.columns[-120:]}) # замена "2015-01-01 00:00:00" на "2015-01" 
df.head(5)

,Показатель,Категория хозяйства,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,КРС,Сельхозпредприятия,РЕСПУБЛИКА КАЗАХСТАН,3400.96,3685.9,4154.43,5203.94,5084.05,6718.83,4235.03,4014.95,4907.52,4274.75,3858.39,6477.35,3884.84,4146.9,4282.08,5408.9,4390.56,8005.48,5105.84,4700.12,5548.88,3958.09,6264.34,9196.32,3739.75,4951.17,6316.68,5751.36,5747.16,10114.01,5944.43,6768.61,5781.59,5885.5,7429.34,9411.91,5555.9,4586.48,7970.28,8130.34,8048.48,14491.87,7543.26,7396.97,9668.6,6730.17,7987.91,11121.61,5666.49,5917.68,8899.55,7784.95,9167.13,16299.73,7164.2,7341.17,10162.65,13532.56,11737.17,14948.7,7041.38,4341.74,10336.12,7419.05,10452.61,16413.66,7973.85,8901.52,10934.83,13130.82,12848.98,18882.81,8135.62,6432.18,9650.38,10482.45,11405.76,16121.49,9114.93,14885.29,13567.02,13473.97,12558.44,20382.82,6709.4,8554.71,12487.58,9184.25,7094.7,16471.11,6373.02,10145.08,8831.12,11123,8927.05,11379.06,7452.75,6836.85,8719.53,9925.26,7684.37,12218.39,6460.2,11289.58,15156.55,9790.74,9021.76,13193.63,6799.94,12303.66,9703.45,11165.56,8179.14,24407.52,9835.22,11955.41,16955.56,10638.42,9612.92,21521.5
1,КРС,Сельхозпредприятия,АКМОЛИНСКАЯ ОБЛАСТЬ,514.75,497.95,863.93,667.81,633.39,600.86,875.47,942.18,856.9,981.04,873.89,1390.18,736.62,845.64,774.36,618.97,701.72,796.48,914.5,736.52,897.89,912.46,867.99,1102.48,660.12,731.14,835,860.71,883.43,963.32,745.3,844.01,678,1025.12,1312.34,919.29,670.25,942.66,847.27,907.92,1002.24,911.62,873.09,1070.9,938.24,832.71,780.14,792.74,993.76,1044.12,1250.31,892.18,1441.82,1249.59,822.67,1007.64,1333,1160.5,1088.61,1164.95,782.49,829.6,1780.71,1077.39,1145.56,1100.69,898.78,829.67,930.63,1135.02,1025.99,1133.29,1141.02,957.47,1261.8,979.49,1029.19,864.06,1056.22,1019.37,1028.55,1254.05,1025.9,1062.94,537.96,1089,1631.34,1183.73,1118.31,1064.21,1240.11,1000.26,1269.72,1136.14,1230.95,1026.95,1294.11,936.76,1229.11,1048.76,1040.48,1181.82,869.84,993.64,938.85,1102.67,1001.63,1079.39,972.07,938.35,978.41,1071.35,1067.76,1119.61,898.07,1382,1133.36,1073.27,1118.19,1332.88
2,КРС,Сельхозпредприятия,АКТЮБИНСКАЯ ОБЛАСТЬ,554.41,504.35,493.56,445.51,585.79,316.47,469.49,303.09,685.51,600.85,603.26,700.48,477.84,221.08,265.59,328.03,384.03,555.07,615.9,619.33,770.79,302.27,1076.31,862.54,473.66,475.3,814.18,638.87,642.96,834.97,902.65,701.17,756.63,726.68,654.31,801.49,703.32,514.47,952.16,1018.39,968.68,845.85,758.18,931.47,1070.07,1278.41,1627.73,1714.64,704.51,899.66,1554.1,1351.44,1050.71,1485.45,814.13,1169.81,2388.34,1595.4,3809.76,3510.19,954.53,481.35,1111.55,1033.96,1939.87,2152.47,1578.87,1426.39,2620.87,2434.4,3247.3,3281.67,580.89,823.34,1221.21,1626.06,1920.41,2637.56,1620.81,2134.96,3425.67,3449.02,3751.75,3827.39,826.17,1132.81,1544.91,1885.46,698.01,4712.69,508.07,592.19,902.26,1479.36,1219.25,658.78,589.8,1275.24,1508.27,1380.18,842.24,3478.29,774.46,764.8,3003.94,1876.68,1547.77,607.03,609.08,873.05,1520.51,1747.09,915.8,1851.96,932.63,945.11,1142.92,1637.64,1180.54,1045.69
3,КРС,Сельхозпредприятия,АЛМАТИНСКАЯ ОБЛАСТЬ,178.3,362.86,352.49,451.79,228.32,708.84,280.55,126.59,629.44,314.28,302.7,273.87,362.96,524.37,549.52,1221.29,663.04,1033.44,877.53,795.88,549.7,524.17,762.84,909.95,361.53,659.43,489.3,413.05,901.47,633.54,986.07,1245.53,678.11,462.36,1124.24,1042.7,626.23,691.69,900.64,546.92,753.49,1249.22,870.13,1085.25,767.07,833.67,621.67,1270.71,647.57,859.73,627.58,510.15,1060.85,748.1,795.62,713.09,917.57,2486.33,1047.68,1716.96,138.84,193.57,1915.13,318.06,1376.06,1100.94,732.62,403.93,1133.23,296.33,528.96,765.77,256.65,247.48,1642.59,204.04,1358.42,1168.3,299.38,1286.74,482.08,219.4,455.71,342.51,185.09,235.07,1692.44,276.34,475.5,1043.31,357.53,225.52,212.32,344.6,413.76,211.75,379.94,109.76,195.04,292.86,204.42,410.94,154.98,100.38,1354.58,189.29,152.57,186.92,141.97,214.08,1055.43,110.45,188.15,172.63,112.31,134.99,1212.02,260.02,129.38,159.66
4,КРС,Сельхозпредприятия,АТЫРАУСКАЯ ОБЛАСТЬ,20.8,0.8,15.28,1.97,2.04,1.32,0.8,1.38,1,0.43,1.47,6.26,7.41,20.63,10.49,11.75,16.13,27.56,15.8,11.24,15.2,3.5,5.1,10.18,7.41,4.52,6.2,3.28,9.99,3.44,9.3,32.91,48.26,21.35,4.52,6.7,2.95,38.66,2.91,23.24,8.43,2.4,19.8,0.3,13.88,1.75,83.62,19.94,5.04,3.28,0.2,7.3,7.88,7.82,0.1,-,2.1,13.76,1.73,1.95,1.8,6.49,7.29,5.7,10.95,5.98,1.57,1.58,19.4,9.32,22.87,-,3.09,3.23,8.92,2.74,3.85,2.11,4.54,1.41,1.69,8.27,13.06,20.24,8.91,9.61,2.14,9.05,5.62,3.5,-,-,2.6,-,5.1,5.7,-,0.06,1.9,-,1.4,4.2,1.4,0.5,1.64,0.54,-,51.62,16.21,17.45,13.52,25.1,13.7,16.08,17.35,41.57,56.59,49.5,40.76,27.22

In [6]:
# проверка значений по столбцам
print(df["Показатель"].unique())
print(df["Категория хозяйства"].unique())
print(df["Регион"].unique())

['КРС' 'Свиньи' 'Лошади' 'Верблюды' 'Птица' 'Молоко' 'Яйца' 'Овцы и козы']
['Сельхозпредприятия' 'Крестьянские или фермерские хозяйства'
 'Хозяйства населения']
['РЕСПУБЛИКА КАЗАХСТАН' '    АКМОЛИНСКАЯ ОБЛАСТЬ'
 '    АКТЮБИНСКАЯ ОБЛАСТЬ' '    АЛМАТИНСКАЯ ОБЛАСТЬ'
 '    АТЫРАУСКАЯ ОБЛАСТЬ' '    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ'
 '    ЖАМБЫЛСКАЯ ОБЛАСТЬ' '    КАРАГАНДИНСКАЯ ОБЛАСТЬ'
 '    КОСТАНАЙСКАЯ ОБЛАСТЬ' '    КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ'
 '    МАНГИСТАУСКАЯ ОБЛАСТЬ' '    ЮЖНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ'
 '    ПАВЛОДАРСКАЯ ОБЛАСТЬ' '    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ'
 '    ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ' '    ГАСТАНА' '    ГАЛМАТЫ'
 '    ГШЫМКЕНТ' '    ТУРКЕСТАНСКАЯ ОБЛАСТЬ' '    ОБЛАСТЬ ЖЕТІСУ'
 '    ОБЛАСТЬ ҰЛЫТАУ' '    ОБЛАСТЬ АБАЙ']

In [7]:
# очистка значений по столбцу "Регион"
df["Регион"] = df["Регион"].str.strip() # удаление лишних пробелов 
df = df[df["Регион"] != "ЮЖНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ"] # удаление ЮКО
df["Регион"].unique()

array(['РЕСПУБЛИКА КАЗАХСТАН', 'АКМОЛИНСКАЯ ОБЛАСТЬ',
       'АКТЮБИНСКАЯ ОБЛАСТЬ', 'АЛМАТИНСКАЯ ОБЛАСТЬ', 'АТЫРАУСКАЯ ОБЛАСТЬ',
       'ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ЖАМБЫЛСКАЯ ОБЛАСТЬ',
       'КАРАГАНДИНСКАЯ ОБЛАСТЬ', 'КОСТАНАЙСКАЯ ОБЛАСТЬ',
       'КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ', 'МАНГИСТАУСКАЯ ОБЛАСТЬ',
       'ПАВЛОДАРСКАЯ ОБЛАСТЬ', 'СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ',
       'ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ГАСТАНА', 'ГАЛМАТЫ', 'ГШЫМКЕНТ',
       'ТУРКЕСТАНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ ЖЕТІСУ', 'ОБЛАСТЬ ҰЛЫТАУ',
       'ОБЛАСТЬ АБАЙ'], dtype=object)

In [8]:
# заполнение пустот
df = df.fillna(0)
# замена "-" на 0
df.replace("-", 0, inplace=True)
df.tail(5)

,Показатель,Категория хозяйства,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
523,Овцы и козы,Хозяйства населения,ГШЫМКЕНТ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.19,109.50,107.50,109.61,110.10,123.3,329.00,91.10,80.10,84.1,84.50,90.90,82.30,88.80,74.00,75.10,84.40,78.30,339.50,87.8,86.2,84.1,84.5,90.9,82.3,88.8,74.0,75.1,84.4,78.3,75.1,88.3,70.4,56.5,45.6,50.6,46.2,42.7,40.7,47.8,50.6,47.9,359.5,89.1,70.7,56.7,44.7,46.4,46.3,42.0,39.7,46.3,48.4,46.2,174.8,88.30,68.30,54.70,43.50,46.40,44.20,42.10,39.70,46.30,48.40,46.20,174.80,88.2,68.3,54.6,43.7,46.4,44.2,42.0,39.7,50.7,49.0,46.2,174.8
524,Овцы и козы,Хозяйства населения,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5199.07,4570.03,4854.96,5303.53,6090.55,5718.8,7403.46,6204.08,5733.43,5593.5,4994.46,4774.99,4728.19,4398.32,4936.91,5536.35,6242.61,5720.59,7478.67,6347.3,5715.5,5566.5,4964.1,4664.4,4818.6,4424.8,4843.6,5517.7,6199.0,5702.3,7601.6,6457.0,5803.5,5615.4,4981.1,4699.8,4817.4,4410.3,4799.2,5529.5,6247.3,5730.3,7829.9,6525.4,5870.5,5506.0,4898.4,4647.5,4709.3,4163.5,4586.1,5378.3,5998.9,5568.9,7787.0,6503.13,5814.36,5337.86,4678.92,4479.58,4572.33,3427.03,3947.03,5202.49,5752.46,5381.07,7348.42,4421.7,4445.2,3904.3,3414.9,3224.1,3182.1,1823.1,2272.9,3341.6,3790.5,4074.5,5796.7
525,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ЖЕТІСУ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3358.6,591.2,1237.6,2046.3,2415.8,2173.3,3951.1,459.09,472.31,2054.34,645.26,493.88,2984.48,527.36,1130.62,2069.94,2129.18,2175.72,3669.04,464.5,477.4,2077.3,656.4,500.8,3064.5,547.4,1156.3,2134.4,2237.4,2093.4,3738.4
526,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ҰЛЫТАУ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,281.8,87.6,137.0,455.0,182.9,184.8,634.3,188.43,84.88,239.96,64.64,489.30,422.24,85.07,207.07,657.05,218.33,214.88,217.80,162.1,220.6,198.3,65.4,490.1,376.7,86.4,213.8,455.5,216.7,169.2,216.1
527,Овцы и козы,Хозяйства населения,ОБЛАСТЬ АБАЙ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1755.4,565.3,754.9,1000.2,666.5,772.7,3695.4,231.31,420.37,495.49,608.37,673.35,1414.13,431.00,533.38,725.74,466.20,584.66,2284.66,238.4,407.8,509.0,638.0,659.1,1385.8,439.4,550.8,741.9,476.9,601.3,2328.2

In [9]:
# Шаг 1: Определение регионов и периодов для замены значений
regions_to_null = ['ОБЛАСТЬ ЖЕТІСУ', 'ОБЛАСТЬ ҰЛЫТАУ', 'ОБЛАСТЬ АБАЙ']
periods_to_null = pd.date_range("2015-01", "2022-05", freq="MS").strftime("%Y-%m") # вышеуказанные регионы не существовали в этот период

# Шаг 2: Маска для замены значений на NaN
mask = (
    df["Регион"].isin(regions_to_null) &
    df.columns[3:].to_series().isin(periods_to_null).any()
)

# Шаг 3: Замена соответствующих значений на NaN
value_columns = df.columns[3:]

for period in periods_to_null:
    if period in value_columns:
        df.loc[df["Регион"].isin(regions_to_null), period] = np.nan
df.tail(5)

,Показатель,Категория хозяйства,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
523,Овцы и козы,Хозяйства населения,ГШЫМКЕНТ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113.19,109.50,107.50,109.61,110.10,123.3,329.00,91.10,80.10,84.1,84.50,90.90,82.30,88.80,74.00,75.10,84.40,78.30,339.50,87.8,86.2,84.1,84.5,90.9,82.3,88.8,74.0,75.1,84.4,78.3,75.1,88.3,70.4,56.5,45.6,50.6,46.2,42.7,40.7,47.8,50.6,47.9,359.5,89.1,70.7,56.7,44.7,46.4,46.3,42.0,39.7,46.3,48.4,46.2,174.8,88.30,68.30,54.70,43.50,46.40,44.20,42.10,39.70,46.30,48.40,46.20,174.80,88.2,68.3,54.6,43.7,46.4,44.2,42.0,39.7,50.7,49.0,46.2,174.8
524,Овцы и козы,Хозяйства населения,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5199.07,4570.03,4854.96,5303.53,6090.55,5718.8,7403.46,6204.08,5733.43,5593.5,4994.46,4774.99,4728.19,4398.32,4936.91,5536.35,6242.61,5720.59,7478.67,6347.3,5715.5,5566.5,4964.1,4664.4,4818.6,4424.8,4843.6,5517.7,6199.0,5702.3,7601.6,6457.0,5803.5,5615.4,4981.1,4699.8,4817.4,4410.3,4799.2,5529.5,6247.3,5730.3,7829.9,6525.4,5870.5,5506.0,4898.4,4647.5,4709.3,4163.5,4586.1,5378.3,5998.9,5568.9,7787.0,6503.13,5814.36,5337.86,4678.92,4479.58,4572.33,3427.03,3947.03,5202.49,5752.46,5381.07,7348.42,4421.7,4445.2,3904.3,3414.9,3224.1,3182.1,1823.1,2272.9,3341.6,3790.5,4074.5,5796.7
525,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ЖЕТІСУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3358.6,591.2,1237.6,2046.3,2415.8,2173.3,3951.1,459.09,472.31,2054.34,645.26,493.88,2984.48,527.36,1130.62,2069.94,2129.18,2175.72,3669.04,464.5,477.4,2077.3,656.4,500.8,3064.5,547.4,1156.3,2134.4,2237.4,2093.4,3738.4
526,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281.8,87.6,137.0,455.0,182.9,184.8,634.3,188.43,84.88,239.96,64.64,489.30,422.24,85.07,207.07,657.05,218.33,214.88,217.80,162.1,220.6,198.3,65.4,490.1,376.7,86.4,213.8,455.5,216.7,169.2,216.1
527,Овцы и козы,Хозяйства населения,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1755.4,565.3,754.9,1000.2,666.5,772.7,3695.4,231.31,420.37,495.49,608.37,673.35,1414.13,431.00,533.38,725.74,466.20,584.66,2284.66,238.4,407.8,509.0,638.0,659.1,1385.8,439.4,550.8,741.9,476.9,601.3,2328.2

In [10]:
# Шаг 1: Определение регионов и периодов для замены значений
regions_to_null2 = ['ГШЫМКЕНТ', 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ']
periods_to_null2 = pd.date_range("2015-01", "2018-05", freq="MS").strftime("%Y-%m") # вышеуказанные регионы не существовали в этот период

# Шаг 2: Маска для замены значений на NaN
mask = (
    df["Регион"].isin(regions_to_null2) &
    df.columns[3:].to_series().isin(periods_to_null2).any()
)

# Шаг 3: Замена соответствующих значений на NaN
value_columns = df.columns[3:]  

for period in periods_to_null2:
    if period in value_columns:
        df.loc[df["Регион"].isin(regions_to_null2), period] = np.nan
df.tail(5)

,Показатель,Категория хозяйства,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
523,Овцы и козы,Хозяйства населения,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,113.19,109.50,107.50,109.61,110.10,123.3,329.00,91.10,80.10,84.1,84.50,90.90,82.30,88.80,74.00,75.10,84.40,78.30,339.50,87.8,86.2,84.1,84.5,90.9,82.3,88.8,74.0,75.1,84.4,78.3,75.1,88.3,70.4,56.5,45.6,50.6,46.2,42.7,40.7,47.8,50.6,47.9,359.5,89.1,70.7,56.7,44.7,46.4,46.3,42.0,39.7,46.3,48.4,46.2,174.8,88.30,68.30,54.70,43.50,46.40,44.20,42.10,39.70,46.30,48.40,46.20,174.80,88.2,68.3,54.6,43.7,46.4,44.2,42.0,39.7,50.7,49.0,46.2,174.8
524,Овцы и козы,Хозяйства населения,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5199.07,4570.03,4854.96,5303.53,6090.55,5718.8,7403.46,6204.08,5733.43,5593.5,4994.46,4774.99,4728.19,4398.32,4936.91,5536.35,6242.61,5720.59,7478.67,6347.3,5715.5,5566.5,4964.1,4664.4,4818.6,4424.8,4843.6,5517.7,6199.0,5702.3,7601.6,6457.0,5803.5,5615.4,4981.1,4699.8,4817.4,4410.3,4799.2,5529.5,6247.3,5730.3,7829.9,6525.4,5870.5,5506.0,4898.4,4647.5,4709.3,4163.5,4586.1,5378.3,5998.9,5568.9,7787.0,6503.13,5814.36,5337.86,4678.92,4479.58,4572.33,3427.03,3947.03,5202.49,5752.46,5381.07,7348.42,4421.7,4445.2,3904.3,3414.9,3224.1,3182.1,1823.1,2272.9,3341.6,3790.5,4074.5,5796.7
525,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ЖЕТІСУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3358.6,591.2,1237.6,2046.3,2415.8,2173.3,3951.1,459.09,472.31,2054.34,645.26,493.88,2984.48,527.36,1130.62,2069.94,2129.18,2175.72,3669.04,464.5,477.4,2077.3,656.4,500.8,3064.5,547.4,1156.3,2134.4,2237.4,2093.4,3738.4
526,Овцы и козы,Хозяйства населения,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281.8,87.6,137.0,455.0,182.9,184.8,634.3,188.43,84.88,239.96,64.64,489.30,422.24,85.07,207.07,657.05,218.33,214.88,217.80,162.1,220.6,198.3,65.4,490.1,376.7,86.4,213.8,455.5,216.7,169.2,216.1
527,Овцы и козы,Хозяйства населения,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1755.4,565.3,754.9,1000.2,666.5,772.7,3695.4,231.31,420.37,495.49,608.37,673.35,1414.13,431.00,533.38,725.74,466.20,584.66,2284.66,238.4,407.8,509.0,638.0,659.1,1385.8,439.4,550.8,741.9,476.9,601.3,2328.2

In [11]:
# проверка корректности замен - количество значений NaN
df.groupby("Регион")[df.columns[90:94]].apply(lambda g: g.isna().sum()).reset_index()

                            Регион  2022-04  2022-05  2022-06  2022-07
0              АКМОЛИНСКАЯ ОБЛАСТЬ        0        0        0        0
1              АКТЮБИНСКАЯ ОБЛАСТЬ        0        0        0        0
2              АЛМАТИНСКАЯ ОБЛАСТЬ        0        0        0        0
3               АТЫРАУСКАЯ ОБЛАСТЬ        0        0        0        0
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
5                          ГАЛМАТЫ        0        0        0        0
6                          ГАСТАНА        0        0        0        0
7                         ГШЫМКЕНТ        0        0        0        0
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ        0        0        0        0
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ        0        0        0        0
11            КОСТАНАЙСКАЯ ОБЛАСТЬ        0        0        0        0
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ        0        0        0        0
13           МАНГИСТАУСКАЯ ОБЛАСТЬ        0        0        0        0
14                    ОБЛАСТЬ АБАЙ       24       24        0        0
15                  ОБЛАСТЬ ЖЕТІСУ       24       24        0        0
16                  ОБЛАСТЬ ҰЛЫТАУ       24       24        0        0
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ        0        0        0        0
18            РЕСПУБЛИКА КАЗАХСТАН        0        0        0        0
19    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
20           ТУРКЕСТАНСКАЯ ОБЛАСТЬ        0        0        0        0

###

In [12]:
# проверка корректности замен - количество значений NaN
df.groupby("Регион")[df.columns[42:46]].apply(lambda g: g.isna().sum()).reset_index()

                            Регион  2018-04  2018-05  2018-06  2018-07
0              АКМОЛИНСКАЯ ОБЛАСТЬ        0        0        0        0
1              АКТЮБИНСКАЯ ОБЛАСТЬ        0        0        0        0
2              АЛМАТИНСКАЯ ОБЛАСТЬ        0        0        0        0
3               АТЫРАУСКАЯ ОБЛАСТЬ        0        0        0        0
4   ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
5                          ГАЛМАТЫ        0        0        0        0
6                          ГАСТАНА        0        0        0        0
7                         ГШЫМКЕНТ       24       24        0        0
8               ЖАМБЫЛСКАЯ ОБЛАСТЬ        0        0        0        0
9    ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
10          КАРАГАНДИНСКАЯ ОБЛАСТЬ        0        0        0        0
11            КОСТАНАЙСКАЯ ОБЛАСТЬ        0        0        0        0
12          КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ        0        0        0        0
13           МАНГИСТАУСКАЯ ОБЛАСТЬ        0        0        0        0
14                    ОБЛАСТЬ АБАЙ       24       24       24       24
15                  ОБЛАСТЬ ЖЕТІСУ       24       24       24       24
16                  ОБЛАСТЬ ҰЛЫТАУ       24       24       24       24
17            ПАВЛОДАРСКАЯ ОБЛАСТЬ        0        0        0        0
18            РЕСПУБЛИКА КАЗАХСТАН        0        0        0        0
19    СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ        0        0        0        0
20           ТУРКЕСТАНСКАЯ ОБЛАСТЬ       24       24        0        0

In [13]:
# преобразованиеи нечисловых столбцов в числовые
non_numeric = df[df.columns[3:]].select_dtypes(exclude='number').columns
print("Non-numeric columns before:", list(non_numeric))
for col in non_numeric:
    df[col] = pd.to_numeric(df[col], errors='coerce')
non_numeric = df[df.columns[3:]].select_dtypes(exclude='number').columns
print("Non-numeric columns after:", list(non_numeric))

Non-numeric columns before: ['2020-02', '2022-10', '2024-02']
Non-numeric columns after: []

In [14]:
# суммрование значений по категориям хозяйств (СХП, КФХ, ХН)
totals = df.groupby(["Показатель", "Регион"])[df.columns[3:]].agg(lambda x: x.sum() if x.notna().any() else np.nan).reset_index()
totals

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Верблюды,АКМОЛИНСКАЯ ОБЛАСТЬ,0.00,0.00,0.40,0.00,0.00,0.00,0.09,1.00,0.00,0.00,0.20,0.00,0.00,0.18,0.28,0.00,0.00,0.40,0.00,0.00,0.65,0.00,0.31,1.00,0.00,0.00,0.00,0.00,0.00,2.01,0.00,1.20,0.00,0.00,2.18,0.39,0.00,0.00,1.04,0.00,0.14,2.08,0.00,0.00,0.00,0.00,0.00,0.30,0.00,0.00,0.00,0.66,0.00,0.33,0.00,0.9,0.00,0.00,0.00,10.08,0.00,0.0,0.00,0.0,0.00,0.54,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.36,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.40,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.0,0.00,0.00,0.0,0.00
1,Верблюды,АКТЮБИНСКАЯ ОБЛАСТЬ,101.98,67.47,374.84,115.59,218.72,14.15,19.77,3.00,39.16,46.16,238.56,463.35,109.04,72.94,384.96,114.35,221.89,10.93,18.79,3.50,38.53,46.64,216.08,472.07,110.32,68.17,380.15,127.12,217.61,14.98,21.26,7.14,44.63,51.78,239.43,513.33,115.70,69.40,371.53,130.17,218.41,14.59,21.76,7.19,45.97,55.48,252.68,527.66,117.94,70.37,385.75,117.80,218.45,15.54,21.78,7.2,47.06,58.02,257.54,543.35,119.80,71.3,396.90,121.8,228.10,15.90,21.9,7.2,63.00,59.90,260.20,552.10,121.60,71.8,398.40,128.50,228.80,13.10,22.50,7.20,63.90,61.90,150.70,554.90,121.30,73.3,404.20,128.70,234.90,13.60,23.60,6.3,49.80,62.4,153.70,552.8,118.07,69.17,384.21,121.01,223.46,11.76,21.39,5.52,48.18,61.39,150.87,531.79,119.50,72.60,391.0,126.1,229.10,12.2,24.10,5.7,49.87,63.00,154.3,538.40
2,Верблюды,АЛМАТИНСКАЯ ОБЛАСТЬ,1.00,0.20,51.60,25.40,0.00,61.90,76.87,95.57,16.09,0.10,10.80,46.78,15.06,13.70,131.80,9.20,17.89,130.12,2.00,0.00,4.99,2.06,4.90,44.48,15.06,23.94,41.60,19.54,3.00,15.14,18.50,14.82,14.52,12.60,9.92,43.11,20.72,2.96,15.24,0.00,1.00,20.03,3.44,7.77,117.25,1.00,0.00,20.34,21.95,3.04,17.91,26.81,9.16,18.80,13.37,0.0,17.29,15.90,4.69,23.10,10.85,9.7,42.75,0.0,6.21,21.10,4.0,2.6,28.10,4.53,79.50,93.18,23.70,11.2,16.00,2.00,3.10,19.62,2.30,4.85,11.18,2.80,9.65,36.44,10.60,11.5,26.10,7.20,12.75,11.20,11.20,27.0,25.26,17.9,21.90,12.5,16.55,16.81,22.78,12.10,12.44,6.85,39.65,17.22,8.85,27.48,0.48,29.72,18.90,17.40,12.5,16.4,11.60,16.7,15.70,24.0,7.70,6.90,5.4,12.60
3,Верблюды,АТЫРАУСКАЯ ОБЛАСТЬ,213.89,167.70,306.60,164.97,342.57,192.00,43.60,113.03,262.37,193.97,308.17,1087.33,325.10,190.60,301.10,154.84,328.50,220.30,66.10,118.20,234.90,196.51,270.92,974.18,303.30,167.41,323.54,182.34,349.10,249.40,57.57,88.40,221.21,199.63,278.80,964.02,305.22,159.62,326.87,159.50,367.20,257.50,60.01,78.10,253.27,332.00,355.05,989.86,280.08,165.05,334.51,134.85,367.97,321.22,126.22,93.7,263.10,366.66,348.54,1041.38,293.40,154.8,339.44,143.6,405.80,308.35,88.5,130.5,575.30,458.70,357.62,998.10,292.76,188.3,487.02,129.28,421.44,351.20,95.77,97.54,624.80,631.65,499.30,1179.66,286.67,189.8,513.16,171.46,402.10,432.22,121.53,126.2,637.50,651.7,482.94,1412.2,307.85,200.59,466.60,182.63,414.56,405.19,184.80,154.96,717.92,719.01,522.83,1164.77,323.81,423.76,441.9,219.1,487.69,446.9,191.43,133.5,730.34,709.68,537.6,930.28
4,Верблюды,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,0.30,0.00,0.00,1.14,6.12,4.70,4.20,1.80,1.80,0.00,6.82,18.78,0.74,0.00,1.80,2.38,1.22,2.40,3.20,2.45,0.90,2.20,0.74,12.46,0.74,2.70,1.80,0.00,0.00,3.00,0.00,0.00,0.90,7.58,1.85,13.27,0.50,0.60,1.27,0.00,0.50,1.70,0.00,0.00,3.54,3.01,11.51,21.95,0.90,0.00,0.75,4.56,4.50,3.20,0.40,8.4,5.40,0.50,2.30,17.77,0.00,0.6,0.60,2.7,0.00,3.10,0.0,0.6,5.85,3.15,3.50,2.80,0.00,0.0,0.90,1.35,0.00,3.30,0.50,0.00,7.60,0.00,2.20,5.50,0.00,0.2,0.00,1.00,0.00,0.00,0.00,0.0,0.00,0.0,0.30,1.7,0.00,0.00,0.00,0.40,0.00,0.00,0.00,0.30,0.00,0.00,0.70,0.50,0.00,0.00,0.0,0.8,0.00,0.0,0.50,0.0,0.00,0.40,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,Яйца,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2387.10,2131.30,1902.2,2182.70,1802.6,1628.40,1957.6,1611.00,1477.40,1715.90,1243.80,1518.40,2385.60,1518.20,1169.10,1960.60,1585.50,1475.30,2242.70,1343.00,1259.10,1569.2,1156.4,1174.80,1957.4,1310.40,973.5,1757.90,961.60,806.3,1780.60
164,Яйца,ПАВЛОДАРСКАЯ ОБЛАСТЬ,9637.30,8361.40,9164.50,10447.60,14083.60,14200.20,14200.20,12827.60,15190.30,11469.40,10976.10,9622.10,8446.10,8446.10,8895.50,10558.10,11831.20,13814.20,14183.70,14087.90,16244.10,12141.90,10834.60,9718.40,8614.40,10405.30,12266.80,13336.20,14884.70,16037.00,16325.40,16077.70,16598.20,15195.10,15267.20,15295.50,13864.00,13348.20,15943.10,18282.40,19924.00,19757.80,19774.80,20310.00,20590.20,18213.50,16278.30,18184.20,17131.70,16581.00,19203.20,20499.90,21971.00,22429.20,22393.20,22997.0,23738.50,21722.60,20525.60,18886.20,18343.50,18280.5,20271.50,20828.1,21491.70,22670.40,24237.5,24123.6,23045.90,20280.20,20677.80,19639.50,19152.10,17237.4,19001.20,20881.80,23706.20,23868.10,25091.30,24541.00,24043.40,20384.00,18617.30,17884.40,18605.20,16439.3,18710.20,20901.70,20292.20,21162.10,22709.00,23348.6,21412.10,18511.5,17998.40,17788.5,16233.80,15161.00,17138.80,17299.10,17224.40,18089.10,18809.10,18631.10,17835.30,16596.80,14092.50,15766.30,16000.70,15324.70,16631.1,16747.1,17414.00,18832.4,18654.70,18689.8,18071.90,16535.50,15899.2,14834.90
165,Яйца,РЕСПУБЛИКА КАЗАХСТАН,325795.20,303234.00,376664.50,400243.30,462679.40,454045.70,454045.70,431318.00,417837.10,371979.40,371135.00,385155.00,345105.30,345105.30,391859.30,399831.00,410066.00,443120.60,433666.30,429021.80,416217.00,367534.50,368180.10,394437.70,339450.00,321737.60,395633.60,403951.60,436228.90,476721.80,473081.10,466755.80,462128.70,419117.70,431897.40,459321.60,405017.70,383273.60,461542.30,455579.30,488942.10,519638.80,518578.50,506386.30,486777.30,450113.10,440205.30,459258.70,423093.10,388183.30,469458.40,465417.00,493579.90,516510.20,498926.20,497167.8,468370.60,431791.40,425242.00,435618.70,382792.20,364651.1,445231.40,446295.6,462576.70,500548.00,492506.5,475752.2,420299.10,366420.10,342399.20,348360.00,312229.30,301140.1,385357.80,392323.80,429830.20,457152.10,482278.80,455426.70,415569.80,394897.90,382200.40,411419.20,369658.60,338444.6,418612.50,432797.60,437817.50,471356.50,475118.70,455318.8,425644.60,398259.5,400621.60,403773.6,337486.30,335939.60,363304.10,365889.80,382432.90,392717.40,385961.80,388656.70,378768.10,371488.70,345780.80,363558.60,338428.60,325559.70,381480.5,368147.0,377486.90,393946.9,397493.70,394871.5,385885.00,371208.00,362418.8,364206.50
166,Яйца,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,37704.50,37570.60,41732.40,52925.70,68018.40,79389.60,79389.60,57759.90,53865.90,32575.20,32921.30,34505.70,34885.40,34885.40,36684.00,52125.90,52177.90,65306.60,74525.80,56924.20,46811.60,37447.80,39640.60,42987.70,40275.50,40661.70,42638.20,53428.60,59419.30,73357.20,84832.50,73107.00,61629.40,49849.70,56814.20,59647.30,53193.30,48863.00,54499.70,60831.60,69441.70,83225.30,92264.60,82390.60,71148.50,64835.90,64677.50,63982.50,58628.30,53443.20,59018.50,65322.20,70363.50,80044.80,89585.90,79866.1,71594.20,59533.50,60792.20,54741.60,51341.60,41390.9,41928.80,51390.8,55041.80,70381.60,80899.6,66342.1,42854.10,22702.90,17435.90,16733.40,18427.40,18751.8,23554.10,36986.70,48238.20,62621.00,71676.10,61380.70,56258.90,49823.00,50452.00,54811.10,54964.70,46460.2,53045.20,59219.50,61589.50,70294.00,83433.00,70544.5,60357.30,50061.1,48334.90,47418.1,42865.20,39820.40,43195.80,48301.20,51580.20,54114.90,54432.30,55153.90,48158.60,43374.80,41853.20,42832.60,41455.00,45002.30,49356.3,49099.2,51500.30,56233.7,58261.10,53762.5,51783.90,47959.40,47352.0,48441.50
167,Яйца,ТУРКЕСТАНСКАЯ ОБЛАСТЬ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18731.20,17928.60,17529.00,16053.00,15376.00,12915.50,13116.90,11514.90,11841.80,17005.20,17679.10,19435.40,19520.50,17827.20,16444.6,14025.90,14428.20,14166.70,14493.40,12755.30,13008.5,18242.60,21190.7,23288.10,22016.30,20365.5,18998.2,17531.10,17798.10,15797.90,15415.70,14817.60,15633.3,20909.80,21679.90,22941.60,21750.60,20437.60,20123.80,17912.60,17440.20,15995.00,17207.40,16537.40,18530.3,23504.00,24571.40,25548.40,22877.80,21223.00,22187.6,19706.80,19155.7,19106.30,20501.2,17007.60,17050.50,21909.20,22528.10,23281.40,20755.30,19872.20,23944.60,24567.30,20771.10,16408.50,18910.90,16642.40,12543.10,21360.2,24469.7,23754.20,22349.7,22437.40,23808.0,22847.10,21639.90,19659.4,19576.80

### Добавление данных по дополнительным потенциальным регрессорам (температура, осадки, поголовье)

In [15]:
# загружаем данные по дополнительным регрессорам
x_vars = pd.read_excel("output data/доп регрессоры обработанные.xlsx")
x_vars.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Температура,АКМОЛИНСКАЯ ОБЛАСТЬ,-12.490323,-10.192857,-5.870968,4.490000,14.574194,20.763333,19.180645,16.529032,11.496667,2.925806,-8.270000,-6.145161,-17.790323,-7.431034,-2.167742,8.633333,13.106452,17.490000,19.106452,20.048387,13.530000,0.370968,-9.976667,-12.954839,-12.264516,-12.989286,-5.403226,5.603333,13.835484,19.546667,18.829032,19.441935,11.596667,2.796774,-1.766667,-10.670968,-18.625806,-14.717857,-8.196774,3.550000,9.506452,17.113333,20.348387,16.616129,11.983333,5.232258,-4.856667,-13.967742,-12.832258,-14.260714,-2.048387,4.333333,13.312903,16.046667,21.670968,18.267742,10.853333,6.922581,-7.266667,-8.038710,-7.838710,-5.851724,-1.441935,9.550000,17.687097,17.110000,21.548387,19.616129,11.306667,5.303226,-5.140000,-13.048387,-17.587097,-14.053571,-7.406452,5.130000,18.716129,18.466667,21.235484,20.074194,10.353333,4.506452,-5.856667,-8.493548,-11.683871,-9.200000,-8.535484,8.873333,15.338710,18.736667,20.583871,17.632258,13.930000,4.709677,-7.810000,-14.154839,-11.600000,-12.278571,-1.867742,5.656667,14.829032,19.796667,24.054839,18.738710,12.866667,6.474194,0.103333,-11.683871,-12.638710,-13.644828,-4.809677,8.026667,10.696774,21.043333,20.270968,17.338710,11.300000,3.832258,-4.343333,-7.638710
1,Температура,АКТЮБИНСКАЯ ОБЛАСТЬ,-13.483871,-11.821429,-5.990323,6.356667,15.609677,25.126667,23.167742,20.732258,16.576667,4.187097,-2.920000,-3.845161,-12.474194,-3.806897,-1.054839,9.783333,16.167742,19.766667,22.332258,24.861290,13.863333,3.980645,-4.056667,-10.980645,-10.119355,-12.132143,-5.500000,5.953333,14.645161,19.843333,23.587097,23.758065,15.550000,5.164516,1.133333,-10.583871,-15.477419,-11.739286,-7.812903,6.746667,16.445161,18.810000,25.893548,20.570968,15.266667,6.838710,-4.470000,-9.922581,-12.296774,-11.685714,-0.583871,8.230000,17.806452,22.266667,24.580645,19.545161,10.923333,8.012903,-4.690000,-7.016129,-5.767742,-5.320690,0.874194,8.100000,17.722581,21.006667,25.261290,20.774194,13.356667,6.409677,-4.913333,-13.645161,-11.145161,-10.978571,-6.683871,7.923333,20.609677,24.920000,23.458065,24.222581,12.753333,5.693548,-3.143333,-6.532258,-9.961290,-5.875000,-6.783871,10.880000,13.245161,20.303333,22.854839,23.264516,15.700000,6.512903,-2.326667,-11.690323,-15.625806,-10.800000,1.522581,10.190000,17.077419,21.763333,24.461290,22.083871,14.703333,7.032258,2.976667,-7.170968,-11.206452,-11.568966,-4.800000,13.513333,13.083871,22.893333,22.912903,20.206452,14.083333,6.667742,-1.520000,-6.419355
2,Температура,АЛМАТИНСКАЯ ОБЛАСТЬ,-5.432258,-1.100000,2.909677,12.126667,17.180645,20.980000,25.564516,22.100000,14.036667,9.780645,2.073333,-3.306452,-2.987097,-3.148276,7.732258,12.073333,15.458065,21.406667,22.287097,21.003226,18.433333,5.293548,-2.963333,-2.283871,-5.312903,-4.157143,2.177419,10.100000,17.093548,20.503333,24.967742,21.006452,16.506667,8.367742,2.550000,-4.222581,-13.251613,-4.892857,6.809677,10.826667,14.519355,20.166667,23.100000,22.412903,14.736667,8.312903,-2.760000,-5.429032,-4.593548,-3.853571,6.267742,11.760000,15.341935,20.540000,26.087097,23.335484,16.643333,8.729032,-0.696667,-3.974194,-5.806452,-1.134483,4.332258,12.516667,17.141935,19.916667,22.961290,22.190323,14.870000,6.377419,-2.143333,-8.358065,-8.954839,-0.435714,3.338710,10.486667,17.938710,21.446667,25.622581,22.696774,17.810000,5.570968,-2.616667,-1.851613,-2.325806,-4.142857,4.490323,14.403333,17.625806,22.333333,24.535484,20.619355,18.470000,8.664516,1.366667,-7.319355,-10.532258,-2.067857,5.938710,9.983333,15.119355,22.590000,25.019355,22.409677,15.486667,10.774194,4.016667,-3.887097,-4.064516,-7.551724,2.812903,11.100000,16.348387,22.023333,23.158065,23.487097,13.726667,9.222581,2.256667,-6.796774
3,Температура,АТЫРАУСКАЯ ОБЛАСТЬ,-6.222581,-6.300000,0.380645,10.856667,19.506452,28.906667,27.177419,25.241935,21.010000,7.493548,2.890000,0.625806,-5.290323,0.913793,5.035484,13.450000,20.316129,24.796667,27.345161,29.809677,17.983333,8.148387,-0.283333,-5.354839,-4.948387,-6.228571,3.996774,12.093333,19.177419,23.656667,28.829032,28.396774,20.850000,9.367742,4.223333,-4.016129,-9.167742,-5.575000,0.035484,11.043333,22.041935,24.373333,31.206452,25.135484,20.056667,11.496774,0.530000,-3.667742,-4.767742,-2.950000,4.625806,12.080000,21.429032,27.906667,27.470968,23.877419,16.740000,12.248387,-0.540000,-0.616129,-1.251613,1.113793,7.316129,10.546667,20.674194,27.763333,30.477419,23.916129,18.573333,11.648387,1.356667,-8.396774,-4.019355,-4.685714,0.577419,14.296667,24.600000,28.723333,29.464516,30.400000,17.750000,9.690323,2.300000,-0.803226,-3.206452,1.550000,1.422581,15.573333,16.700000,25.863333,26.912903,28.851613,20.850000,11.203226,2.740000,-5.838710,-5.906452,-4.203571,8.600000,15.023333,21.867742,25.703333,28.151613,27.638710,19.133333,11.235484,6.943333,-1.596774,-5.661290,-2.872414,2.522581,17.776667,17.341935,27.453333,28.264516,25.774194,19.956667,10.648387,3.096667,-2.612903
4,Температура,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,-11.845161,-8.928571,-4.406452,7.470000,17.100000,25.283333,22.690323,20.348387,17.446667,4.545161,0.296667,-2.441935,-10.851613,-2.900000,0.441935,10.676667,16.338710,20.636667,23.274194,25.925806,13.583333,5.145161,-3.126667,-11.767742,-10.774194,-10.392857,-2.719355,7.980000,14.841935,18.463333,23.287097,24.038710,16.316667,6.048387,1.816667,-6.216129,-11.158065,-10.914286,-9.212903,7.183333,17.841935,19.786667,25.661290,21.267742,16.820000,7.832258,-3.556667,-9.187097,-12.061290,-9.771429,-1.025806,9.406667,18.364516,22.246667,22.109677,19.822581,12.273333,9.680645,-2.470000,-4.864516,-3.632258,-3.434483,4.541935,7.936667,16.993548,20.733333,26.093548,20.532258,13.883333,7.793548,-2.263333,-13.816129,-9.435484,-11.489286,-5.061290,9.776667,21.606452,24.526667,25.264516,26.090323,13.463333,7.138710,-0.033333,-6.687097,-8.861290,-4.217857,-4.993548,11.566667,12.441935,21.080000,23.209677,24.258065,15.576667,8.145161,-0.013333,-7.848387,-12.964516,-8.321429,4.400000,10.850000,18.887097,20.720000,23.793548,22.816129,15.490000,7.645161,2.840000,-4.877419,-12.048387,-10.824138,-4.632258,14.926667,13.332258,23.853333,24.132258,21.151613,15.246667,8.261290,0.423333,-5.496774

In [16]:
# проверка регрессоров
x_vars['Показатель'].unique()

array(['Температура', 'Поголовье: КРС', 'Поголовье: лошади',
       'Поголовье: овцы и козы', 'Поголовье: свиньи',
       'Поголовье: птица домашняя', 'Поголовье: верблюды', 'Осадки'],
      dtype=object)

In [17]:
# объединение двух датасетов
df_combined = pd.concat([totals, x_vars], ignore_index=True)
df_combined.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
101,Овцы и козы,ПАВЛОДАРСКАЯ ОБЛАСТЬ,770.23,628.54,658.58,874.45,831.39,1592.40,914.11,922.82,1048.26,1014.66,803.45,1907.28,786.56,692.52,620.68,901.22,1118.31,1305.96,1016.85,876.76,1032.76,986.44,868.49,1386.48,479.16,553.62,685.69,940.31,983.09,1206.26,618.02,883.94,1071.62,912.96,989.53,1463.56,471.34,570.00,594.61,951.34,962.30,1246.12,809.75,835.91,1008.18,835.98,975.59,1503.25,447.47,506.77,614.75,1022.63,1002.64,1339.54,601.66,854.15,1071.57,832.02,1043.31,1645.14,443.71,506.75,608.23,961.58,965.47,1266.70,706.71,896.26,1201.12,836.60,1046.11,1767.30,451.68,536.48,690.77,991.49,971.12,1270.99,604.60,882.02,1054.88,858.83,1018.01,1534.05,447.66,510.30,621.55,995.05,1062.24,1307.95,599.20,866.86,1052.15,825.77,981.95,1487.04,405.53,408.10,541.90,868.53,789.74,1084.78,544.43,774.64,947.27,704.65,886.38,1416.76,351.38,419.37,514.38,899.78,774.78,1138.67,537.89,799.28,949.76,711.61,916.89,1525.30
88,Овцы и козы,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,841.83,2153.16,2420.82,2383.56,2794.03,5496.94,5033.24,4639.56,5743.42,4951.05,4762.12,10419.20,1051.72,2103.10,2362.92,2439.05,2829.97,6387.17,4649.26,4469.01,5382.15,4151.32,4772.47,11551.79,1360.95,2064.72,2489.59,2615.28,3034.78,6952.07,4210.06,4056.49,5158.76,3229.92,5032.93,14137.89,1259.36,1838.86,2310.37,2546.02,2896.47,7359.69,3902.78,3450.28,3712.38,2648.30,3730.97,11749.89,1137.74,1823.08,2309.31,2602.94,2799.68,6455.68,3961.21,3232.09,3732.28,2288.86,3691.77,11176.95,1102.13,1873.62,2360.15,2661.29,2826.42,6337.60,3946.00,3126.77,3729.06,2424.13,3545.79,10901.57,1126.23,1914.55,2402.29,2702.01,2916.91,6417.48,3914.18,3045.44,4725.77,2721.23,3539.35,10916.10,1174.70,1852.14,2453.07,2674.12,2850.71,1497.79,1361.38,762.78,1649.88,915.15,1367.84,3722.70,451.87,703.67,1116.56,831.48,884.88,1474.31,1531.46,610.03,1728.84,943.43,1309.82,3207.45,463.04,727.88,1115.63,856.29,898.75,1520.02,1404.39,749.40,1738.77,941.21,1485.16,3244.57
228,Поголовье: лошади,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,371836.00,361519.00,354338.00,344109.00,331390.00,324073.00,313576.00,8970.00,9035.00,8955.00,9040.00,10845.00,11079.00,11818.00,11334.00,11573.00,14133.00,15580.00,15664.00,368020.00,366762.00,364970.00,402444.00,442303.00,492263.00,476613.00,400620.00,385348.00,369076.00,357557.00,366751.00
102,Овцы и козы,РЕСПУБЛИКА КАЗАХСТАН,17429.73,15965.57,25342.99,21907.05,20597.75,37409.49,24157.41,27474.67,34201.49,28335.67,31345.02,49128.27,17505.24,15909.58,25960.76,22396.92,21324.33,38967.20,23554.97,27320.78,34858.36,27259.67,32464.04,54082.25,17781.61,16102.60,26367.01,21780.90,21173.74,38877.01,22469.33,26475.66,33547.06,26899.81,33408.02,61038.34,17920.05,15816.03,26885.76,21997.47,21127.73,40641.78,22644.33,26253.43,31914.82,26421.83,32052.33,59985.70,17776.61,15997.80,27311.62,22344.01,21754.70,39316.14,22723.67,26344.93,32568.02,26744.42,31772.48,59269.73,17948.56,16054.72,27686.04,22027.72,21214.93,39515.21,22976.22,26331.50,33391.95,27178.08,31954.38,60368.12,18458.38,16565.42,28322.34,22478.34,21763.05,40520.23,22036.82,26251.92,34900.27,28320.87,32250.86,61202.38,18732.23,16524.76,28382.72,22145.42,22155.53,40449.42,21606.91,26122.52,33603.31,28082.62,32550.08,61934.42,17175.72,15200.78,24949.60,19693.47,20067.04,35284.14,18352.68,22937.63,30136.82,24751.17,28598.86,51143.99,14970.27,13853.80,24294.75,18859.58,18815.04,35436.25,16580.03,21686.84,29706.62,22752.08,27979.84,53372.71
21,КРС,АКМОЛИНСКАЯ ОБЛАСТЬ,4455.35,3654.20,4287.08,3923.21,3849.70,4074.13,2221.96,2151.76,2728.61,2395.25,3662.75,5106.13,4579.64,3819.89,4206.27,3828.08,3924.54,4350.84,2114.79,1956.69,2985.68,2358.76,3577.39,4459.83,4503.74,3825.10,4314.56,4079.14,4158.71,4558.46,1963.82,2090.28,2836.24,2583.69,3945.28,4485.16,4561.83,4100.47,4088.16,4155.35,4217.88,4467.70,2074.30,2328.67,3133.57,2328.78,3416.97,4237.37,4842.70,4172.34,4504.06,4161.80,4610.32,4844.60,2054.78,2294.43,3630.24,2683.31,3746.00,4634.26,4725.79,3943.70,5103.01,4354.19,4303.06,4689.79,2149.18,2114.57,3124.73,2673.82,3701.49,4665.79,5086.82,4117.67,4610.40,4273.19,4196.89,4475.86,2318.82,2354.47,3237.95,2779.45,3717.30,4504.14,4492.66,4272.80,5020.74,4509.63,4302.61,4698.11,2513.31,2344.06,3497.82,2634.34,3916.65,4466.95,4202.81,3338.63,3743.36,3532.80,3492.94,3879.85,1925.70,1964.12,2644.50,2501.99,3437.92,3751.14,4035.37,3446.55,3779.21,3691.05,3574.86,3951.41,2029.47,2412.70,2909.66,2608.27,3649.19,4253.58
80,Молоко,ПАВЛОДАРСКАЯ ОБЛАСТЬ,13983.10,17224.70,24506.80,28898.00,47215.80,47102.00,47102.00,42784.90,31585.20,26929.30,20094.20,19828.20,14237.90,14237.90,24821.90,28800.60,39263.70,48460.00,47129.00,42589.10,32141.40,27195.60,20601.00,20792.10,14247.60,18158.20,25676.60,29670.00,39882.90,49280.50,46828.20,43654.10,32609.30,27803.80,20647.50,20648.30,15285.00,18772.10,26371.30,30577.70,40931.30,51654.90,48614.20,44655.90,33681.90,28551.80,21518.40,21454.30,15825.90,19357.00,27133.70,31724.10,41839.10,52820.70,49100.20,45243.60,34237.00,29447.10,22473.10,22903.50,16516.90,20593.30,28367.50,33161.70,42917.20,53942.80,50134.40,46247.40,35369.60,30417.70,23463.10,23731.60,17501.20,21356.30,29422.20,34026.90,43839.30,54868.20,52956.90,47473.10,37023.60,31802.50,24787.50,25463.70,17728.70,21426.10,29742.30,34392.60,44273.90,55680.70,53801.10,49479.00,38563.90,32697.30,25548.10,25684.70,11480.30,12771.10,16787.70,19053.80,23256.80,26870.80,26414.70,24770.80,20605.80,18498.00,15369.70,15974.10,13562.10,13681.10,16963.30,19686.40,22567.50,26529.50,26499.90,24757.90,20555.90,18701.10,16120.00,17260.20
224,Поголовье: лошади,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11215.00,10656.00,10621.00,10560.00,10524.00,10480.00,14092.00,13844.00,13661.00,13886.00,14795.00,14696.00,15191.00,15218.00,15154.00,15126.00,15082.00,14967.00,14830.00,14966.00,13689.00,13530.00,13798.00,14716.00,14610.00,14613.00,14550.00,14499.00,14464.00,14323.00,14282.00,14119.00,13878.00,13777.00,14074.00,14972.00,14788.00,14558.00,14128.00,14005.00,13926.00,13821.00,13728.00,13666.00,13529.00,13377.00,13619.00,14517.00,14399.00,16185.00,16015.00,15904.00,15817.00,15809.00,15660.00,492.00,392.00,391.00,391.00,389.00,388.00,332.00,388.00,387.00,507.00,450.00,561.00,17426.00,17229.00,16965.00,16848.00,17114.00,16999.00,20226.00,20056.00,19945.00,20016.00,19892.00,19740.00
290,Поголовье: птица домашняя,ОБЛАСТЬ ҰЛЫТАУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136235.00,129979.00,114062.00,112919.00,109318.00,107170.00,105360.00,54159.00,53426.00,46204.00,39656.00,38696.00,84484.00,64106.00,59978.00,59167.00,57500.00,56353.00,54840.00,95964.00,94556.00,93006.00,92266.00,91248.00,90861.00,90421.00,100380.00,131300.00,142148.00,138131.00,147460.00
154,Яйца,ГШЫМКЕНТ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15517.40,13403.20,11548.50,11249.30,11596.40,9974.00,11101.70,11368.50,10015.00,11206.70,9191.00,9945.50,8472.40,8302.20,8838.30,9956.60,11490.80,11729.80,12692.50,12835.20,11126.90,12348.60,12316.80,13841.20,11621.10,12427.30,13872.30,14834.90,15336.40,15516.80,15853.60,15016.40,13061.70,12620.50,12567.30,12888.70,11595.50,13755.10,13987.80,11044.80,12566.50,13012.60,13252.20,11067.60,10828.40,12485.00,10284.80,12448.80,11963.40,11273.30,12035.10,12962.00,11915.10,11528.80,12606.30,14195.20,14601.80,14352.90,14040.70,14902.00,10165.00,13566.30,15129.70,14133.70,16361.70,15111.10,14970.10,14208.60,14391.80,13738.50,13958.40,15634.10,14532.90,13793.40,14567.70,14597.20,15961.00,17495.60,17266.10
68,Молоко,ГАЛМАТЫ,315.10,253.90,476.00,594.90,272.90,317.00,317.00,325.00,336.90,908.80,516.90,533.10,343.30,343.30,243.40,255.30,379.30,275.50,368.20,385.50,371.90,1090.70,601.60,558.50,343.50,242.30,249.80,256.80,360.30,261.50,349.60,400.90,375.20,1113.20,654.70,560.10,343.70,243.30,249.20,258.40,329.90,270.00,351.90,412.90,391.10,1116.80,686.20,575.80,385.30,247.30,253.20,261.20,331.00,273.90,354.00,416.60,388.10,1112.10,747.20,248.50,385.60,63.90,66.40,72.30,169.40,269.50,161.50,207.60,191.10,458.60,284.30,237.00,58.50,55.90,58.70,60.60,142.80,204.70,130.80,161.00,152.90,408.90,248.50,153.70,38.10,38.00,40.20,42.90,101.80,164.30,95.70,131.20,135.20,358.10,240.60,153.20,31.40,30.60,0.70,30.40,30.40,44.50,38.40,8.00,9.00,85.10,79.40,80.20,48.20,48.30,16.10,28.60,29.10,27.30,28.40,27.50,22.90,28.70,28.20,38.60

In [18]:
# загружаем данные по дополнительным регрессорам (индексы цен на говядину и баранину)
x_vars2 = pd.read_excel("output data/индекс цен говядина и баранина обработанные.xlsx")
x_vars2.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Цена: Говядина,РЕСПУБЛИКА КАЗАХСТАН,100.1,99.7997,99.7997,99.300701,98.704897,98.704897,98.803602,99.198817,99.298015,100.986082,101.793970,102.099352,101.895154,101.997049,101.793055,102.505606,102.915628,103.224375,103.121151,103.946120,105.401366,105.717570,106.457593,106.883423,108.486675,112.609168,113.847869,114.758652,115.906239,116.485770,117.534142,118.827017,120.371768,120.973627,122.062390,123.283014,123.406297,124.146735,125.388202,126.391308,127.023264,127.531357,127.913951,128.425607,129.067735,129.713074,130.491352,131.404792,131.667601,132.194272,132.194272,133.516214,136.186539,139.318829,141.269293,145.507371,148.708534,151.236579,151.690288,152.752120,153.515881,154.744008,157.374656,160.522149,162.287893,164.235348,164.563818,165.222074,166.709072,167.375909,167.878036,168.381671,168.381671,169.560342,171.255946,172.283481,172.800332,173.664333,177.484949,178.727343,181.586981,182.131742,182.678137,182.495459,182.677954,182.860632,186.700706,188.567713,189.887687,191.216900,192.746636,193.903115,197.393372,199.367305,200.364142,201.165598,202.372592,203.586827,207.862151,209.525048,211.620299,213.948122,214.803914,216.092738,218.037572,218.473648,218.692121,219.348198,220.006242,220.226248,221.107153,221.991582,222.213574,222.658001,222.658001,223.103317,223.326420,223.773073,223.996846,224.892833
1,Цена: Говядина,АКМОЛИНСКАЯ ОБЛАСТЬ,100.0,100.0000,100.0000,99.800000,99.800000,99.800000,99.800000,99.800000,99.800000,99.700200,99.700200,99.700200,99.700200,99.700200,99.700200,99.700200,99.700200,99.700200,99.700200,104.685210,104.685210,104.789895,107.724012,107.724012,107.724012,117.742345,117.742345,117.860088,117.860088,122.928072,122.928072,122.928072,122.928072,122.928072,122.928072,126.738842,126.738842,126.738842,129.780574,132.246405,135.684811,135.820496,138.536906,138.536906,138.536906,139.922275,139.922275,139.922275,140.621887,140.621887,140.621887,140.621887,143.434324,150.749475,151.050974,152.410433,152.410433,153.934537,154.088471,154.088471,154.088471,159.481568,160.916902,169.445498,169.614943,171.650323,171.650323,171.650323,171.821973,171.821973,171.821973,171.821973,171.650151,171.650151,178.687807,184.763193,184.763193,184.763193,191.414668,191.414668,191.414668,191.414668,191.414668,191.606082,191.606082,191.606082,195.438204,195.438204,209.118878,209.327997,209.746653,209.746653,209.956400,210.166356,210.166356,216.051014,216.051014,216.267065,216.483332,220.380032,225.008013,225.233021,225.233021,236.044206,235.100029,235.570229,235.334659,235.569993,235.569993,235.569993,236.512273,236.512273,242.898105,242.898105,246.298678,251.224652,253.485674,253.485674,253.485674,253.485674
2,Цена: Говядина,АКТЮБИНСКАЯ ОБЛАСТЬ,100.0,100.0000,100.0000,100.000000,100.000000,103.200000,103.200000,103.200000,103.200000,103.922400,104.026322,104.026322,104.026322,104.026322,104.026322,104.026322,104.962559,104.962559,104.962559,104.962559,105.277447,105.277447,106.751331,106.751331,111.234887,116.574162,119.371942,119.371942,120.446289,120.446289,122.614322,124.943994,127.817706,129.479336,129.608816,134.533951,134.533951,134.937553,137.771241,139.975581,142.495142,142.495142,142.495142,142.495142,143.492608,144.640548,144.785189,144.785189,144.785189,144.785189,145.509115,145.509115,146.091151,151.788706,152.547650,152.547650,154.530769,155.303423,156.390547,157.016109,157.958206,158.747997,163.510437,168.415750,169.089413,176.698437,177.581929,178.292256,180.075179,180.075179,180.435329,181.157071,181.700542,182.245644,182.974626,183.523550,184.074121,185.362639,185.548002,187.217934,187.966806,187.966806,188.342739,189.096110,189.285207,189.285207,193.070911,193.263982,196.162941,201.851667,203.668332,207.130693,213.344614,216.331439,218.494753,219.587227,223.759384,224.654422,228.248892,229.390137,231.454648,231.454648,232.380467,235.401413,235.636814,235.636814,235.636814,237.286272,237.286272,239.421848,239.182426,243.966075,243.966075,242.746245,242.746245,242.018006,243.470114,244.930935,245.910658,248.123854
3,Цена: Говядина,АЛМАТИНСКАЯ ОБЛАСТЬ,100.0,100.0000,100.0000,98.700000,98.700000,98.700000,98.700000,98.700000,98.798700,98.798700,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.541038,103.644579,110.899699,112.341395,114.475882,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.819309,114.934129,115.163997,115.163997,115.163997,117.927933,118.045861,117.691723,117.691723,117.691723,117.691723,118.750949,121.719722,124.275837,124.275837,124.275837,124.275837,129.371146,133.511023,134.712622,134.712622,139.966414,140.526280,147.974173,148.862018,152.881292,154.257224,154.257224,155.645539,158.914095,158.914095,169.243511,169.412755,169.412755,171.953946,171.953946,171.953946,173.157624,173.330781,173.330781,179.050697,179.050697,179.050697,179.408798,181.561704,181.743266,182.288496,182.470784,184.477963,184.477963,184.477963,184.477963,194.993206,195.188200,195.188200,197.140082,197.928642,198.324499,201.101042,203.112053,204.533837,204.942905,204.942905,205.147848,230.791329,231.022120,235.642562,238.470273,238.947214,238.947214,238.947214,238.947214,238.947214,238.947214,238.947214,239.186161,239.425347,240.143623,232.939314,232.939314,232.939314,232.007557,230.383504,230.613888,230.613888,234.303710
4,Цена: Говядина,АТЫРАУСКАЯ ОБЛАСТЬ,100.0,100.0000,100.0000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.400000,100.400000,100.400000,100.400000,100.701200,100.902602,101.003505,101.003505,101.003505,101.003505,101.003505,101.306516,101.509129,102.219692,104.570745,106.453019,107.517549,108.270172,109.028063,109.028063,109.028063,111.099596,115.099182,115.099182,115.099182,115.099182,115.214281,115.675138,116.253514,117.881063,117.763182,117.409892,124.102256,124.226358,124.723264,124.847987,124.847987,126.845555,127.479783,129.391979,129.780155,129.780155,131.986418,132.646350,134.370753,134.370753,134.505123,137.060721,136.512478,136.512478,137.741090,138.429796,139.537234,140.653532,138.684382,138.684382,138.684382,138.684382,138.684382,139.377804,139.377804,139.377804,139.377804,142.862249,144.148010,144.292158,144.436450,144.580886,146.171276,146.609790,148.955546,148.955546,148.955546,148.955546,149.998235,150.898225,155.274273,155.429547,155.584977,158.852262,161.076193,161.398346,163.819321,166.112791,166.943355,167.611129,168.113962,168.282076,170.806307,170.977113,172.515907,174.758614,175.807166,176.862009,184.820799,185.929724,187.417162,188.916499,194.395078,194.783868,197.705626,199.682682,203.876018,203.876018,200.614002,202.018300,200.402154,201.203762,202.008577,202.210586

In [19]:
x_vars2['Показатель'].unique()

array(['Цена: Говядина', 'Цена: Баранина'], dtype=object)

In [20]:
# объедтинение датасетов
df_combined = pd.concat([df_combined, x_vars2], ignore_index=True)
df_combined.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
348,Цена: Говядина,ГАСТАНА,9.970000e+01,9.960030e+01,9.960030e+01,9.960030e+01,9.491909e+01,9.586828e+01,9.567654e+01,9.558086e+01,9.538970e+01,9.453119e+01,9.500385e+01,9.690393e+01,9.690393e+01,9.690393e+01,9.690393e+01,1.015553e+02,1.013522e+02,1.021630e+02,1.021630e+02,1.076798e+02,1.095104e+02,1.106055e+02,1.111585e+02,1.109362e+02,1.118237e+02,1.158493e+02,1.164286e+02,1.172436e+02,1.191195e+02,1.191195e+02,1.222166e+02,1.289385e+02,1.295832e+02,1.289353e+02,1.291932e+02,1.293223e+02,1.294517e+02,1.304873e+02,1.314007e+02,1.325833e+02,1.339091e+02,1.340430e+02,1.337750e+02,1.337750e+02,1.347114e+02,1.351155e+02,1.351155e+02,1.351155e+02,1.347102e+02,1.368655e+02,1.382342e+02,1.386489e+02,1.423924e+02,1.443859e+02,1.468405e+02,1.508052e+02,1.523132e+02,1.552072e+02,1.561384e+02,1.561384e+02,1.584805e+02,1.602238e+02,1.675941e+02,1.714487e+02,1.707629e+02,1.704214e+02,1.712735e+02,1.711022e+02,1.753798e+02,1.753798e+02,1.764321e+02,1.767849e+02,1.767849e+02,1.789063e+02,1.790853e+02,1.790853e+02,1.799807e+02,1.769210e+02,1.778056e+02,1.804727e+02,1.851650e+02,1.851650e+02,1.862760e+02,1.868348e+02,1.870216e+02,1.866476e+02,1.903805e+02,1.964727e+02,1.972586e+02,1.994285e+02,1.994285e+02,2.012233e+02,2.092722e+02,2.140855e+02,2.140855e+02,2.155841e+02,230.028243,228.188017,229.785333,234.610825,236.018490,237.906638,240.999424,242.92742,245.599621,243.143625,241.684763,241.443079,2.424089e+02,2.424089e+02,2.436209e+02,2.433773e+02,2.438640e+02,2.433763e+02,2.433763e+02,2.426462e+02,2.433741e+02,2.438609e+02,2.441047e+02,2.448370e+02
213,Поголовье: лошади,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,1.157870e+05,1.142670e+05,1.159730e+05,1.271330e+05,1.346640e+05,1.393980e+05,1.384430e+05,1.377390e+05,1.364060e+05,1.349790e+05,1.326820e+05,1.311090e+05,1.298240e+05,1.288960e+05,1.303260e+05,1.418490e+05,1.509210e+05,1.558190e+05,1.539820e+05,1.528490e+05,1.514370e+05,1.503310e+05,1.476510e+05,1.465460e+05,1.425050e+05,1.441140e+05,1.466210e+05,1.603630e+05,1.682860e+05,1.728240e+05,1.713390e+05,1.702500e+05,1.695820e+05,1.681660e+05,1.651260e+05,1.669010e+05,1.654190e+05,1.643670e+05,1.671330e+05,1.814010e+05,1.914030e+05,1.883830e+05,1.873690e+05,1.862060e+05,1.850830e+05,1.835180e+05,1.805880e+05,1.799060e+05,1.783930e+05,1.776570e+05,1.804650e+05,1.958060e+05,2.076650e+05,1.989130e+05,1.975880e+05,1.964450e+05,1.937680e+05,1.920930e+05,1.889000e+05,1.928920e+05,1.928920e+05,1.914060e+05,1.909410e+05,1.948970e+05,2.110180e+05,2.266230e+05,2.264200e+05,2.251410e+05,2.240810e+05,2.207330e+05,2.193660e+05,2.161830e+05,2.231840e+05,2.215060e+05,2.210190e+05,2.254720e+05,2.424680e+05,2.601220e+05,2.533780e+05,2.520380e+05,2.506850e+05,2.473930e+05,2.457150e+05,2.423530e+05,2.504600e+05,2.490180e+05,2.497830e+05,2.545570e+05,2.738120e+05,2.933080e+05,2.832690e+05,2.821950e+05,2.803730e+05,2.765730e+05,2.750280e+05,2.712920e+05,12491.000000,12626.000000,12654.000000,12676.000000,13180.000000,14152.000000,15218.000000,15229.00000,15222.000000,16396.000000,17221.000000,17276.000000,2.654440e+05,2.642100e+05,2.653190e+05,2.714740e+05,2.911860e+05,3.124900e+05,3.321730e+05,3.007070e+05,2.981640e+05,2.954850e+05,2.935020e+05,2.899910e+05
357,Цена: Баранина,АКТЮБИНСКАЯ ОБЛАСТЬ,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,9.690000e+01,9.690000e+01,9.690000e+01,9.690000e+01,9.883800e+01,9.893684e+01,9.893684e+01,1.001241e+02,1.002242e+02,1.004247e+02,1.004247e+02,1.007259e+02,1.007259e+02,1.007259e+02,1.007259e+02,1.007259e+02,1.007259e+02,1.034455e+02,1.034455e+02,1.067558e+02,1.069693e+02,1.093226e+02,1.095413e+02,1.098699e+02,1.098699e+02,1.125068e+02,1.125068e+02,1.125068e+02,1.134068e+02,1.134068e+02,1.155615e+02,1.170638e+02,1.170638e+02,1.217464e+02,1.217464e+02,1.299034e+02,1.299034e+02,1.299034e+02,1.299034e+02,1.299034e+02,1.301632e+02,1.304235e+02,1.304235e+02,1.304235e+02,1.304235e+02,1.308148e+02,1.308148e+02,1.326462e+02,1.343706e+02,1.382674e+02,1.382674e+02,1.382674e+02,1.385439e+02,1.389595e+02,1.389595e+02,1.409050e+02,1.418913e+02,1.431683e+02,1.431683e+02,1.431683e+02,1.599190e+02,1.599190e+02,1.618381e+02,1.626472e+02,1.626472e+02,1.639484e+02,1.647682e+02,1.659215e+02,1.728902e+02,1.737547e+02,1.746235e+02,1.775921e+02,1.820319e+02,1.904053e+02,1.911670e+02,1.932698e+02,1.938496e+02,1.954004e+02,1.961820e+02,1.961820e+02,1.967705e+02,2.064123e+02,2.105406e+02,2.118038e+02,2.134982e+02,2.158467e+02,2.158467e+02,2.171418e+02,2.195303e+02,2.210671e+02,2.210671e+02,223.056661,223.056661,227.517794,229.792972,233.010073,235.806194,238.635868,239.11314,239.113140,236.243783,236.243783,242.858608,2.428586e+02,2.428586e+02,2.428586e+02,2.523301e+02,2.523301e+02,2.641896e+02,2.641896e+02,2.655106e+02,2.718828e+02,2.732422e+02,2.746084e+02,2.746084e+02
316,Осадки,АЛМАТИНСКАЯ ОБЛАСТЬ,8.900000e+00,2.130000e+01,4.860000e+01,6.150000e+01,3.600000e+01,6.320000e+01,4.400000e+00,2.160000e+01,1.080000e+01,4.550000e+01,5.990000e+01,2.750000e+01,4.100000e+01,6.200000e+00,4.290000e+01,8.830000e+01,1.675000e+02,6.490000e+01,7.880000e+01,3.000000e-01,1.890000e+01,6.000000e+01,5.860000e+01,6.070000e+01,1.590000e+01,3.110000e+01,4.170000e+01,9.950000e+01,4.570000e+01,6.220000e+01,8.900000e+00,1.330000e+01,1.630000e+01,2.210000e+01,4.030000e+01,1.570000e+01,2.670000e+01,2.560000e+01,7.730000e+01,5.960000e+01,7.570000e+01,2.200000e+01,6.960000e+01,2.190000e+01,1.320000e+01,2.730000e+01,2.910000e+01,1.410000e+01,1.830000e+01,3.230000e+01,1.760000e+01,9.090000e+01,4.750000e+01,4.470000e+01,6.900000e+00,2.830000e+01,4.420000e+01,3.490000e+01,2.530000e+01,3.420000e+01,1.160000e+01,4.900000e+01,2.340000e+01,9.970000e+01,8.280000e+01,2.700000e+01,2.570000e+01,4.760000e+01,4.800000e+00,4.000000e+00,9.100000e+00,1.030000e+01,6.900000e+00,3.380000e+01,6.620000e+01,4.290000e+01,4.890000e+01,1.180000e+01,1.580000e+01,1.580000e+01,1.600000e+00,4.070000e+01,3.770000e+01,7.300000e+00,1.570000e+01,2.300000e+01,9.480000e+01,3.190000e+01,8.710000e+01,2.900000e+01,1.220000e+01,1.110000e+01,1.500000e+00,3.000000e+01,6.670000e+01,7.400000e+00,20.800000,20.000000,34.300000,37.100000,26.500000,9.400000,42.800000,40.80000,37.200000,51.300000,39.700000,48.000000,3.560000e+01,3.730000e+01,7.570000e+01,7.340000e+01,9.070000e+01,1.420000e+01,6.970000e+01,6.800000e+00,3.270000e+01,6.040000e+01,3.620000e+01,3.030000e+01
286,Поголовье: птица домашняя,ГАЛМАТЫ,1.333400e+04,9.294000e+03,8.610000e+03,7.727000e+03,8.093000e+03,7.891000e+03,7.891000e+03,7.390000e+03,6.945000e+03,6.540000e+03,6.017000e+03,6.017000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.963000e+03,5.761000e+03,5.495000e+03,5.495000e+03,5.495000e+03,5.495000e+03,5.495000e+03,5.495000e+03,5.485000e+03,5.485000e+03,5.485000e+03,5.478000e+03,5.478000e+03,5.478000e+03,5.478000e+03,5.336000e+03,5.336000e+03,5.336000e+03,5.009000e+03,5.369000e+03,5.584000e+03,5.534000e+03,5.639000e+03,5.869000e+03,5.817000e+03,5.623000e+03,5.713000e+03,5.683000e+03,5.770000e+03,5.729000e+03,5.695000e+03,5.695000e+03,5.695000e+03,5.710000e+03,5.710000e+03,5.613000e+03,5.558000e+03,5.528000e+03,5.503000e+03,5.483000e+03,5.463000e+03,5.443000e+03,6.896000e+03,6.876000e+03,6.856000e+03,6.836000e+03,6.816000e+03,6.796000e+03,6.776000e+03,6.766000e+03,6.756000e+03,6.746000e+03,6.736000e+03,6.726000e+03,9.536000e+03,9.516000e+03,9.506000e+03,9.486000e+03,9.466000e+03,9.466000e+03,9.456000e+03,9.436000e+03,9.416000e+03,9.297000e+03,9.297000e+03,9.297000e+03,9.297000e+03,9.390000e+03,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.00000,31.000000,31.000000,31.000000,31.000000,8.641000e+03,8.564000e+03,8.475000e+03,8.355000e+03,8.266000e+03,8.179000e+03,8.094000e+03,8.009000e+03,7.924000e+03,7.839000e+03,7.756000e+03,7.675000e+03
196,Поголовье: КРС,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,2.512430e+05,2.603830e+05,2.664920e+05,2.743440e+05,2.812770e+05,2.805000e+05,2.696170e+05,2.667480e+05,2.637850e+05,2.599110e+05,2.565990e+05,2.561240e+05,2.690280e+05,2.717320e+05,2.775320e+05,2.857480e+05,2.931130e+05,2.927820e+05,2.848490e+05,2.818130e+05,2.791110e+05,2.747660e+05,2.714120e+05,2.701520e+05,2.842580e+05,2.923770e+05,2.987770e+05,3.072390e+05,3.147240e+05,3.139020e+05,3.011770e+05,2.982180e+05,2.953810e+05,2.916040e+05,2.890260e+05,3.096350e+05,3.100700e+05,3.133150e+05,3.200950e+05,3.286050e+05,3.360250e+05,3.253860e+05,3.226670e+05,3.193830e+05,3.164240e+05,3.123160e+05,3.092210e+05,3.239680e+05,3.245190e+05,3.280880e+05,3.351540e+05,3.434700e+05,3.508710e+05,3.521160e+05,3.440480e+05,3.407610e+05,3.377550e+05,3.335920e+05,3.304110e+05,3.323810e+05,3.323810e+05,3.311700e+05,3.350140e+05,3.423130e+05,3.505630e+05,3.653580e+05,3.615880e+05,3.590150e+05,3.559430e+05,3.525830e+05,3.483420e+05,3.444510e+05,3.425510e+05,3.419810e+05,3.507500e+05,3.585000e+05,3.670510e+05,3.795710e+05,3.870790e+05,3.846130e+05,3.833730e+05,3.813000e+05,3.770930e+05,3.735230e+05,3.606570e+05,3.591010e+05,3.679690e+05,3.756950e+05,3.842840e+05,3.945510e+05,4.203180e+05,4.187380e+05,4.151520e+05,4.110250e+05,4.066370e+05,4.028600e+05,6485.000000,6209.000000,6312.000000,6374.000000,6451.000000,6612.000000,6773.000000,6773.00000,6943.000000,8082.000000,7993.000000,7870.000000,3.119470e+05,2.996020e+05,3.031220e+05,3.154690e+05,3.258280e+05,3.310670e+05,3.487130e+05,4.234310e+05,4.198880e+05,4.201350e+05,4.147700e+05,4.086430e+05
229,Поголовье: лошади,РЕСПУБЛИКА КАЗАХСТАН,1.819378e+06,1.886719e+06,1.976977e+06,2.177690e+06,2.308349e+06,2.310386e+06,2.228859e+06,2.184637e+06,2.132512e+06,2.093812e+06,2.037528e+06,1.984189e+06,2.031061e+06,2.017723e+06,2.119775e+06,2.333908e+06,2.473610e+06,2.474548e+06,2.376812e+06,2.324417e+06,2.269657e+06,2.228689e+06,2.168286e+06,2.113151e+06,2.192576e+06,2.201855e+06,2.307829e+06,2.542749e+06,2.688944e+06,2.687858e+06,2.563032e+06,2.508551e+06,2.445342e+06,2.397202e+06,2.332126e+06,2.395047e+06,2.373710e+06,2.356938e+06,2.463540e+06,2.706018e+06,2.862558e+06,2.865920e+06,2.731496e+06,2.676867e+06,2.612488e+06,2.569771e+06,2.502391e+06,2.623713e+06,2.602423e+06,2.588886e+06,2.702181e+06,2.960610e+06,3.135153e+06,3.108883e+06,2.961345e+06,2.905678e+06,2.831324e+06,2.777935e+06,2.706732e+06,2.825851e+06,2.853564e+06,2.805125e+06,2.789796e+06,2.912513e+06,3.184547e+06,3.381907e+06,3.372194e+06,3.228394e+06,3.168690e+06,3.088993e+06,3.034011e+06,2.955534e+06,3.138705e+06,3.093214e+06,3.080459e+06,3.203557e+06,3.504166e+06,3.708773e+06,3.701064e+06,3.531249e+06,3.471502e+06,3.388722e+06,3.330806e+06,3.256422e+06,3.490525e+06,3.443669e+06,3.422913e+06,3.548849e+06,3.881677e+06,4.110488e+06,4.093999e+06,3.935209e+06,3.874026e+06,3.785601e+06,3.728079e+06,3.650744e+06,273044.000000,274835.000000,275956.000000,277201.000000,287380.000000,303357.000000,311912.000000,312549.00000,312375.000000,340778.000000,345976.000000,346392.000000,3.853147e+06,3.864871e+06,3.827076e+06,3.985124e+06,4.267566e+06,4.483555e+06,4.488493e+06,4.313452e+06,4.274920e+06,4.193227e+06,4.132104e+06,4.072288e+06
259,Поголовье: свиньи,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,2.235000e+03,2.390000e+03,2.757000e+03,2.923000e+03,3.145000e+03,3.188000e+03,2.575000e+03,2.527000e+03,2.607000e+03,2.507000e+03,2.485000e+03,2.490000e+03,2.607000e+03,2.588000e+03,2.975000e+03,3.140000e+03,3.397000e+03,3.417000e+03,2.568000e+03,2.519000e+03,2.574000e+03,2.415000e+03,2.383000e+03,2.384000e+03,2.326000e+03,2.318000e+03,2.694000e+03,2.800000e+03,3.062000e+03,3.131000e+03,2.235000e+03,2.161000e+03,2.081000e+03,1.936000e+03,2.058000e+03,2.302000e+03,2.183000e+03,2.177000e+03,2.581000e+03,2.677000e+03,2.929000e+03,2.049000e+03,1.892000e+03,1.821000e+03,1.992000e+03,1.849000e+03,1.977000e+03,2.322000e+03,2.232000e+03,2.270000e+03,2.732000e+03,2.834000e+03,3.041000e+03,3.238000e+03,2.733000e+03,2.647000e+03,2.842000e+03,2.725000e+03,2.858000e+03,2.546000e+03,2.546000e+03,2.465000e+03,2.457000e+03,2.920000e+03,2.970000e+03,3.211000e+03,2.146000e+03,2.046000e+03,1.929000e+03,1.867000e+03,1.701000e+03,1.876000e+03,1.652000e+03,1.558000e+03,1.490000e+03,1.947000e+03,1.972000e+03,1.913000e+03,1.643000e+03,1.498000e+03,1.384000e+03,1.321000e+03,1.128000e+03,1.083000e+03,1.263000e+03,1.166000e+03,1.098000e+03,1.237000e+03,1.240000e+03,1.106000e+03,1.183000e+03,1.041000e+03,9.260000e+02,8.680000e+02,7.690000e+02,7.420000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.630000e+02,6.410000e+02,5.930000e+02,8.090000e+02,8.740000e+02,7.700000e+02,6.460000e+02,6.400000e+02,6.010000e+02,5.960000e+02,4.630000e+02,4.100000e+02
171,Температура,АТЫРАУСКАЯ ОБЛАСТЬ,-6.222581e+00,-6.300000e+00,3.806452e-01,1.085667e+01,1.950645e+01,2.890667e+01,2.717742e+01,2.524194e+01,2.101000e+01,7.493548e+00,2.890000e+00,6.258065e-01,-5.290323e+00,9.137931e-01,5.035484e+00,1.345000e+01,2.031613e+01,2.479667e+01,2.734516e+01,2.980968e+01,1.798333e+01,8.148387e+00,-2.833333e-01,-5.354839e+00,-4.948387e+00,-6.228571e+00,3.996774e+00,1.209333e+01,1.917742e+01,2.365667e+01,2.882903e+01,2.839677e+01,2.085000e+01,9.367742e+00,4.223333e+00,-4.016129e+00,-9.167742e+00,-5.575000e+00,3.548387e-02,1.104333e+01,2.204194e+01,2.437333e+01,3.120645e+01,2.513548e+01,2.005667e+01,1.149677e+01,5.300000e-01,-3.667742e+00,-4.767742e+00,-2.950000e+00,4.625806e+00,1.208000e+01,2.142903e+01,2.790667e+01,2.747097e+01,2.387742e+01,1.674000e+01,1.224839e+01,-5.400000e-01,-6.161290e-01,-1.251613e+00,1.113793e+00,7.316129e+00,1.054667e+01,2.067419e+01,2.776333e+01,3.047742e+01,2.391613e+01,1.857333e+01,1.164839e+01,1.356667e+00,-8.396774e+00,-4.019355e+00,-4.685714e+00,5.774194e-01,1.429667e+01,2.460000e+01,2.872333e+01,2.946452e+01,3.040000e+01,1.775000e+01,9.690323e+00,2.300000e+00,-8.032258e-01,-3.206452e+00,1.550000e+00,1.422581e+00,1.557333e+01,1.670000e+01,2.586333e+01,2.691290e+01,2.885161e+01,2.085000e+01,1.120323e+01,2.740000e+00,-5.838710e+00,-5.906452,-4.203571,8.600000,15.023333,21.867742,25.703333,28.151613,27.63871,19.133333,11.235484,6.943333,-1.596774,-5.661290e+00,-2.872414e+00,2.522581e+00,1.777667e+01,1.734194e+01,2.745333e+01,2.826452e+01,2.577419e+01,1.995667e+01,1.064839e+01,3.096667e+00,-2.612903e+00
310,Поголовье: верблюды,ОБЛАСТЬ ЖЕТІСУ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.656000e+03,1.610000e+03,1.610000e+03,1.616000e+03,1.615000e+03,1.615000e+03,1.612000e+03,103.000000,616.000000,616.000000,615.000000,619.000000,749.000000,749.000000,746.00000,706.000000,704.000000,704.000000,664.000000,1.792000e+03,1.951000e+03,1.819000e+03,1.834000e+03,1.841000e+03,1.861000e+03,7.470000e+02,6.850000e+02,6.850000e+02,6.850000e+02,6.850000e+02,6.850000e+02

In [21]:
df_combined['Показатель'].unique()

array(['Верблюды', 'КРС', 'Лошади', 'Молоко', 'Овцы и козы', 'Птица',
       'Свиньи', 'Яйца', 'Температура', 'Поголовье: КРС',
       'Поголовье: лошади', 'Поголовье: овцы и козы', 'Поголовье: свиньи',
       'Поголовье: птица домашняя', 'Поголовье: верблюды', 'Осадки',
       'Цена: Говядина', 'Цена: Баранина'], dtype=object)

In [22]:
# загружаем данные по дополнительным регрессорам (индексы цен на молоко и яйца)
x_vars3 = pd.read_excel("output data/индекс цен молоко и яйца обработанные.xlsx")
x_vars3.head(5)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
0,Цена: Молоко,РЕСПУБЛИКА КАЗАХСТАН,100.5,100.6005,99.192093,96.414714,94.197176,91.653852,88.995890,88.461915,88.550377,89.612982,92.659823,94.698339,95.834719,96.313893,97.854915,98.442045,97.851392,97.068581,96.486170,96.968600,98.617067,100.392174,102.600802,104.345015,105.492811,108.235624,108.452095,108.343643,108.451986,107.909726,107.370178,106.833327,107.260660,109.298613,111.703182,112.708511,114.399139,115.314332,116.698104,116.231311,115.650155,114.609303,113.348601,113.688647,114.029713,116.196277,117.939221,119.354492,120.906100,122.115161,122.115161,122.359392,121.502876,120.652356,119.928442,120.528084,121.612837,125.990899,128.384726,129.668573,131.483933,133.324708,134.257981,134.123723,133.453105,134.921089,135.595694,136.138077,137.635596,139.424859,141.934506,144.347393,146.945646,149.002885,149.449893,149.748793,149.599044,149.150247,149.001097,149.150098,150.939899,153.053058,156.879384,160.644490,162.893512,166.314276,169.141619,173.539301,176.489469,178.607343,178.785950,179.858666,182.016970,186.567394,194.776359,198.477110,205.026855,206.667070,208.733740,210.403610,211.245225,208.921527,209.966135,209.126270,209.544523,211.011335,211.644369,213.337523,214.404211,215.476232,214.183375,214.183375,214.183375,213.326641,213.753295,214.608308,215.895958,218.486709,220.453089,222.878073
1,Цена: Молоко,АКМОЛИНСКАЯ ОБЛАСТЬ,100.7,100.7000,100.297200,100.196903,96.289224,95.133753,94.372683,95.222037,94.841149,94.651467,95.314027,98.078134,100.333931,100.534599,102.846894,103.155435,102.123881,101.102642,101.001539,100.900538,102.212245,103.029943,105.811751,107.610551,107.825772,108.904030,109.121838,107.921498,110.295770,110.295770,107.207489,109.030016,110.665466,112.436114,113.785347,115.492127,115.607620,115.954442,126.158433,125.275324,125.776426,125.524873,126.026972,126.026972,126.026972,126.531080,126.657611,131.343943,132.657382,132.657382,131.596123,138.965506,134.796541,136.818489,135.313486,135.990053,136.398023,137.216411,139.274658,139.692482,141.089406,142.641390,142.641390,145.779500,147.237295,147.237295,151.507177,151.961699,154.241124,154.241124,154.703847,155.632070,156.254599,158.598418,158.598418,158.598418,158.598418,158.598418,158.598418,158.439819,160.182657,159.862292,161.460915,162.106759,162.593079,163.568637,163.568637,174.364167,175.235988,177.514056,177.514056,178.756654,179.650438,181.446942,199.954530,200.954303,205.375298,205.375298,205.991423,208.875303,209.293054,208.665175,208.665175,208.456510,208.456510,208.456510,208.456510,208.456510,208.456510,208.456510,208.456510,208.039597,207.831557,207.415894,205.549151,205.754700,210.487058,210.908032,211.962572,212.386498
2,Цена: Молоко,АКТЮБИНСКАЯ ОБЛАСТЬ,100.0,99.5000,99.997500,101.997450,101.997450,99.651509,99.751160,99.751160,99.052902,99.647219,99.647219,99.647219,99.647219,100.942633,100.034150,100.034150,96.432920,96.143621,96.239765,96.624724,97.494347,99.639222,97.048603,97.242700,100.646194,107.892720,107.137471,107.137471,107.137471,105.423272,108.480546,109.131430,109.131430,110.113613,110.774294,110.774294,111.549714,114.115358,114.115358,114.115358,114.115358,115.598857,117.101643,117.101643,117.101643,117.101643,117.101643,117.101643,116.047728,116.627966,110.563312,109.789369,113.631997,112.950205,112.950205,111.707753,111.707753,118.075095,118.075095,122.325798,114.252295,114.252295,120.536172,119.692418,119.692418,138.484128,138.761096,141.813840,142.522910,136.251902,138.159428,138.159428,146.172675,146.172675,151.727237,151.575509,157.486954,157.486954,158.746850,161.286800,161.286800,162.577094,162.577094,162.577094,173.794913,179.008761,181.156866,194.019003,194.795079,187.977252,190.420956,194.229375,197.142816,202.662815,203.676129,203.065100,203.065100,203.065100,217.888853,217.888853,241.420849,210.277559,219.109217,219.109217,241.239248,247.752707,247.752707,262.865622,263.391354,263.391354,263.391354,263.391354,263.918136,257.056265,257.313321,264.518094,264.518094,264.518094,268.750384,268.750384
3,Цена: Молоко,АЛМАТИНСКАЯ ОБЛАСТЬ,99.3,99.3000,99.101400,99.002299,97.418262,96.444079,94.997418,94.142441,95.648720,96.126964,99.972042,102.671288,106.572797,107.212233,107.426658,107.856364,107.317083,105.278058,102.961941,101.520474,101.825035,101.926860,103.965397,105.524878,106.896702,109.889809,109.340360,107.372234,106.405884,105.235419,104.393536,104.184748,105.539150,107.649933,110.448831,112.216013,112.552661,117.279873,120.094590,121.535725,120.684975,119.960865,119.121139,118.406412,118.643225,119.592370,121.386256,121.871801,123.212391,125.183789,125.183789,125.183789,124.683054,124.184322,124.184322,125.177796,127.681352,136.236003,130.105383,130.625804,134.152701,132.677021,132.809698,132.145650,131.617067,133.591323,133.324140,134.657382,136.138613,137.772276,142.318762,145.449774,148.940569,154.749251,153.975505,154.283456,153.820605,152.743861,150.758191,150.155158,151.806865,155.146616,157.318669,160.622361,163.192318,171.515127,180.433913,181.336083,182.968108,183.151076,182.967925,183.516828,187.554199,190.179957,196.075536,197.251989,204.550313,208.641319,208.224037,206.558244,209.450060,209.031160,209.031160,207.986004,208.193990,211.525094,215.755595,220.502219,221.163725,230.231438,227.929124,226.333620,226.107286,224.976750,235.100703,233.219898,235.552097,239.792035,245.067459,248.743471
4,Цена: Молоко,АТЫРАУСКАЯ ОБЛАСТЬ,101.2,102.1108,102.212911,102.110698,103.438137,102.196879,101.992486,102.196471,102.298667,102.298667,102.196368,101.889779,101.686000,94.873038,96.296133,99.762794,100.660659,99.855374,98.257688,96.783823,98.138796,99.022045,100.210310,92.894957,92.709167,99.476937,99.576413,100.273448,100.273448,98.969894,98.870924,99.068665,99.564009,100.061829,101.062447,104.296445,105.026521,105.446627,105.446627,105.446627,105.341180,105.025156,103.974905,103.662980,103.766643,106.049509,106.261608,106.474132,107.112976,110.861931,110.972792,110.972792,110.750847,110.418594,109.203990,109.640806,109.531165,109.421634,109.421634,109.859320,110.408617,110.519026,110.629545,110.629545,110.850804,110.407400,110.738623,111.403054,111.514457,104.712076,104.816788,115.822550,115.938373,116.865880,117.216477,117.802560,121.218834,120.855178,120.734322,120.734322,121.337994,121.823346,121.945169,122.311005,122.922560,123.414250,123.414250,123.167422,123.536924,122.054481,121.932426,120.469237,121.071583,121.071583,121.071583,121.071583,122.766586,124.362551,124.362551,124.362551,124.362551,123.243288,122.010855,122.010855,122.010855,122.010855,122.010855,122.010855,123.596996,125.698145,125.698145,125.698145,125.698145,123.309881,123.309881,121.830162,121.830162,121.830162,121.830162,123.901275

In [23]:
x_vars3['Показатель'].unique()

array(['Цена: Молоко', 'Цена: Яйца'], dtype=object)

In [24]:
# объединение датасетов
df_combined = pd.concat([df_combined, x_vars3], ignore_index=True)
df_combined.sample(10)

,Показатель,Регион,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10,2024-11,2024-12
46,Лошади,ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,956.37,968.54,1543.85,1609.77,1869.51,3189.46,1653.06,3080.85,3208.70,2260.490,2734.980000,4221.210000,1104.150000,1167.190000,1650.030000,1689.320000,1839.950000,3557.080000,1811.460000,3722.010000,3771.530000,2375.570000,2749.880000,4714.610000,1010.360000,1246.190000,1758.460000,1958.390000,1984.970000,3605.920000,2695.120000,4564.400000,4865.080000,2700.170000,3275.990000,4599.740000,1112.110000,1477.040000,2187.540000,2029.130000,2892.820000,4052.600000,2844.020000,4368.170000,5701.150000,4225.000000,5153.540000,5586.730000,1300.510000,1708.620000,2161.800000,2259.570000,3162.360000,5352.180000,2953.430000,4760.140000,6203.220000,4040.690000,4018.530000,6020.580000,1439.180000,1801.760000,2241.560000,2370.440000,3163.030000,6278.200000,3418.640000,5174.610000,6567.100000,4396.530000,4775.190000,7244.110000,1540.560000,1876.860000,2370.440000,2416.630000,3361.350000,6435.150000,3577.130000,5485.740000,6658.740000,3906.260000,5049.060000,6828.920000,1579.140000,2079.510000,2286.540000,2830.090000,3619.080000,1837.970000,1321.610000,1702.190000,2389.480000,1602.000000,2077.680000,2125.910000,709.020000,825.750000,537.160000,939.180000,1105.530000,1968.690000,1453.780000,1700.280000,2674.200000,1832.700000,2352.480000,2460.590000,702.950000,819.010000,545.550000,987.470000,1167.970000,2232.180000,1568.380000,1694.580000,2388.170000,1805.180000,2375.430000,3235.580000
72,Молоко,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,3611.20,6283.70,9171.80,18468.20,40125.20,27562.60,27562.60,24379.50,23077.80,13281.300,12183.500000,12846.300000,3766.900000,3766.900000,9282.100000,19203.100000,36087.700000,41605.900000,30025.400000,24670.700000,23603.200000,13720.800000,9587.800000,9150.400000,3768.000000,6626.600000,9455.800000,19353.300000,36260.900000,41713.000000,30211.800000,24783.600000,23941.400000,13870.600000,11204.100000,10373.600000,3788.000000,6645.100000,9451.900000,19752.500000,36485.900000,43005.400000,30686.600000,24906.000000,23986.500000,14389.000000,11138.600000,10340.800000,3859.400000,6725.500000,9599.600000,19889.300000,36800.400000,43293.000000,30666.200000,25051.300000,24098.400000,14475.300000,11230.600000,10789.900000,3821.500000,6792.500000,9732.200000,19897.600000,37000.100000,43136.500000,30843.000000,24679.200000,24326.700000,14482.400000,11328.000000,10851.000000,3741.300000,6477.500000,9545.100000,19853.100000,36981.200000,43723.600000,31746.200000,25265.700000,23958.700000,14271.400000,11409.200000,10915.700000,3834.800000,6703.300000,9352.800000,20036.100000,37348.800000,43976.500000,32058.200000,25460.700000,24141.000000,14515.100000,11393.000000,11220.600000,3462.600000,6402.100000,8743.500000,18963.100000,34443.000000,38874.400000,28863.600000,22362.300000,21378.500000,12484.100000,10823.800000,9752.200000,3219.200000,6442.500000,8738.000000,18832.400000,34459.100000,39307.000000,27028.600000,20199.800000,19579.400000,11174.100000,9415.900000,9712.400000
17,Верблюды,ПАВЛОДАРСКАЯ ОБЛАСТЬ,0.00,0.00,0.00,0.96,0.00,0.00,0.00,0.00,1.60,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,1.860000,0.000000,1.200000,0.000000,0.370000,0.120000,0.000000,0.000000,0.000000,0.000000,0.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.010000,0.800000,0.000000,0.000000,0.740000,0.000000,0.000000,0.000000,0.300000,0.000000,0.000000,0.000000,0.380000,0.560000,0.000000,1.000000,0.000000,0.940000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.430000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.530000,5.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.420000,0.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.000000,0.000000
89,Овцы и козы,ГАЛМАТЫ,3.09,1.16,4.00,4.08,5.12,3.96,0.00,0.00,1.52,9.160,0.560000,0.120000,0.000000,1.040000,7.320000,11.840000,0.320000,0.680000,0.000000,2.080000,0.320000,0.000000,0.840000,0.000000,0.360000,1.960000,2.000000,3.960000,5.400000,0.080000,0.640000,1.880000,1.680000,4.840000,2.840000,3.280000,10.320000,1.520000,0.640000,0.200000,3.600000,2.200000,0.120000,0.400000,0.080000,6.640000,7.200000,1.000000,0.320000,0.400000,1.040000,0.000000,4.520000,0.880000,0.120000,0.440000,0.040000,0.360000,2.920000,11.000000,0.000000,0.800000,0.200000,0.400000,0.100000,0.000000,0.100000,0.000000,3.500000,0.300000,1.800000,5.200000,0.200000,0.000000,0.900000,3.200000,0.700000,0.100000,0.000000,0.000000,0.100000,0.600000,0.400000,0.000000,0.000000,0.000000,0.100000,0.000000,0.500000,0.300000,0.400000,0.000000,3.300000,0.400000,0.400000,0.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,0.700000,1.900000,0.000000,0.400000,0.000000,0.400000,0.100000,0.300000,0.000000,0.000000,0.000000,1.500000,0.000000,0.900000
361,Цена: Баранина,ЖАМБЫЛСКАЯ ОБЛАСТЬ,100.00,100.00,100.00,96.80,96.80,96.80,96.80,96.80,96.80,100.188,101.089692,101.089692,101.089692,101.089692,100.483154,100.483154,100.483154,100.483154,100.483154,100.483154,100.483154,102.090884,103.315975,103.315975,103.419291,104.763742,105.916143,107.293053,109.009742,109.009742,109.009742,109.881819,111.969574,113.985026,114.099011,114.099011,114.099011,114.327209,114.441537,115.471510,115.471510,115.471510,115.471510,115.471510,115.471510,115.471510,116.510754,117.675862,117.675862,117.793537,118.853679,120.874192,124.863040,126.236534,129.013737,131.981053,133.300864,134.633872,137.326550,137.601203,137.601203,137.738804,139.391670,142.597678,145.449632,145.595081,149.671744,149.671744,149.671744,149.671744,149.671744,149.671744,151.168461,151.319630,153.892063,156.046552,160.103763,160.744178,163.155340,164.950049,170.063501,170.063501,174.145025,174.145025,174.319170,174.319170,181.466256,203.968071,204.579976,204.784555,205.808478,206.631712,206.631712,206.838344,207.252021,207.459273,207.459273,207.459273,207.459273,207.874191,214.110417,214.110417,214.110417,217.964404,218.836262,218.836262,218.836262,219.055098,219.055098,219.055098,219.055098,219.055098,219.055098,219.274153,219.054879,218.835824,219.054660,219.054660,219.273715,219.492989
196,Поголовье: КРС,КЫЗЫЛОРДИНСКАЯ ОБЛАСТЬ,251243.00,260383.00,266492.00,274344.00,281277.00,280500.00,269617.00,266748.00,263785.00,259911.000,256599.000000,256124.000000,269028.000000,271732.000000,277532.000000,285748.000000,293113.000000,292782.000000,284849.000000,281813.000000,279111.000000,274766.000000,271412.000000,270152.000000,284258.000000,292377.000000,298777.000000,307239.000000,314724.000000,313902.000000,301177.000000,298218.000000,295381.000000,291604.000000,289026.000000,309635.000000,310070.000000,313315.000000,320095.000000,328605.000000,336025.000000,325386.000000,322667.000000,319383.000000,316424.000000,312316.000000,309221.000000,323968.000000,324519.000000,328088.000000,335154.000000,343470.000000,350871.000000,352116.000000,344048.000000,340761.000000,337755.000000,333592.000000,330411.000000,332381.000000,332381.000000,331170.000000,335014.000000,342313.000000,350563.000000,365358.000000,361588.000000,359015.000000,355943.000000,352583.000000,348342.000000,344451.000000,342551.000000,341981.000000,350750.000000,358500.000000,367051.000000,379571.000000,387079.000000,384613.000000,383373.000000,381300.000000,377093.000000,373523.000000,360657.000000,359101.000000,367969.000000,375695.000000,384284.000000,394551.000000,420318.000000,418738.000000,415152.000000,411025.000000,406637.000000,402860.000000,6485.000000,6209.000000,6312.000000,6374.000000,6451.000000,6612.000000,6773.000000,6773.000000,6943.000000,8082.000000,7993.000000,7870.000000,311947.000000,299602.000000,303122.000000,315469.000000,325828.000000,331067.000000,348713.000000,423431.000000,419888.000000,420135.000000,414770.000000,408643.000000
367,Цена: Баранина,СЕВЕРО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,100.00,100.00,100.00,100.00,100.00,100.00,99.60,99.60,99.60,99.600,110.456400,110.456400,110.898226,110.898226,110.898226,110.898226,110.898226,110.898226,110.898226,110.898226,115.445053,114.059712,112.690996,112.690996,112.690996,112.690996,112.690996,113.367142,113.480509,113.480509,113.480509,113.480509,113.480509,115.296197,115.296197,116.679751,116.679751,116.679751,116.796431,117.380413,118.554217,119.028434,119.028434,119.028434,119.266491,119.505024,119.744034,122.019171,122.019171,122.385228,122.385228,124.465777,125.337038,125.963723,125.963723,131.632090,134.659628,136.948842,137.359689,137.497048,138.047036,138.185083,142.330636,147.169878,150.554785,150.855894,151.308462,151.308462,153.275472,153.735298,153.889034,154.042923,154.351009,154.351009,154.505360,158.367994,158.367994,160.268410,162.992973,164.459909,164.624369,170.880095,170.880095,170.880095,170.880095,171.221855,187.145488,187.332633,195.949935,202.024383,206.064870,215.955984,223.730399,223.730399,231.337233,231.337233,231.337233,232.031245,232.495307,232.960298,234.358060,234.358060,234.358060,234.592418,234.592418,234.592418,235.765380,240.009157,240.249166,240.249166,240.249166,240.249166,240.008917,238.808872,239.525299,239.046248,238.807202,238.568395,241.431215,241.431215
320,Осадки,КАРАГАНДИНСКАЯ ОБЛАСТЬ,43.10,20.50,44.70,45.30,82.70,31.90,46.00,17.40,27.80,35.600,47.600000,77.900000,30.400000,17.300000,20.200000,23.200000,35.200000,62.500000,125.000000,20.300000,17.500000,49.900000,44.900000,40.100000,20.900000,33.200000,25.600000,36.200000,16.800000,40.100000,25.700000,10.900000,24.200000,41.300000,22.500000,50.600000,19.600000,14.200000,62.100000,33.800000,23.800000,44.200000,26.000000,88.500000,34.500000,72.800000,47.900000,15.600000,10.300000,31.800000,16.200000,43.700000,9.000000,57.100000,5.000000,22.000000,37.700000,50.600000,35.700000,57.100000,56.500000,42.900000,8.900000,16.700000,37.700000,65.300000,68.800000,77.700000,30.600000,16.100000,43.400000,12.200000,12.100000,33.900000,51.100000,5.700000,28.800000,24.500000,18.000000,20.500000,29.900000,26.100000,55.900000,28.000000,12.200000,18.600000,53.100000,11.400000,22.500000,15.000000,32.200000,4.400000,5.500000,32.300000,43.500000,15.800000,34.400000,20.400000,35.400000,12.800000,13.000000,20.900000,2.600000,90.000000,90.000000,66.700000,36.100000,42.200000,29.300000,27.400000,25.200000,25.800000,80.900000,48.200000,124.100000,30.100000,13.600000,46.200000,36.500000,27.700000
29,КРС,ЖАМБЫЛСКАЯ ОБЛАСТЬ,2731.22,3109.06,2538.81,3379.88,2921.49,4463.86,2630.68,5015.59,4328.26,3390.990,6204.390000,9155.180000,2849.600000,3465.720000,2512.550000,3361.080000,3131.110000,4330.220000,2500.200000,4770.170000,4706.990000,3994.850000,7482.210000,10776.430000,2801.630000,3613.580000,2986.620000,3889.830000,3225.320000,4938.750000,3020.770000,6214.420000,4766.250000,3759.100000,7659.690000,12361.140000,3344.150000,3469.060000,3764.110000,4235.170000,3987.960000,5617.410000,3037.290000,5958.720000,6625.490000,4273.050000,8403.440000,14040.980000,3522.730000,3955.720000,3812.240000,4002.030000,3643.790000,6743.480000,2939.640000,6283.390000,6597.540000,4631.610000,8549.750000,13992.310000,5080.540000,3712.290000,3201.180000,3785.630000,3603.820000,5699.560000,2727.860000,6356.410000,5911.200000,4469.290000,8337.790000,18563.010000,5027.670000,3773.230000,4028.020000,3834.950000,3667.130000,6818.330000,2836.190000,6156.520000,7752.350000,5194.390000,9319.700000,18239.400000,3492.390000,4136.760000,4490.670000,3787.260000,3604.130000,6492.440000,2855.430000,5713.080000,6481.040000,4660.370000,9108.730000,15042.700000,2390.220000,3044.260000,3804.650000,3140.490000,3111.630000,4948.860000,2328.740000,4401.590000,4215.450000,3407.930000,5637.510000,15066.610000,2452.320000,3173.150000,4104.820000,3231.510000,3215.250000,4352.030000,2461.280000,4488.080000,4264.390000,3418.050000,5708.500000,15350.760000
258,Поголовье: свиньи,КОСТАНАЙСКАЯ ОБЛАСТЬ,164021.00,151109.00,160653.00,172126.00,186847.00,194843.00,244176.00,231586.00,224705.00,209239.000,187137.000000,161459.000000,165694.000000,153041.000000,161702.000000,174734.000000,189744.000000,197187.000000,205634.000000,195535.000000,190965.000000,179582.000000,161983.000000,146929.000000,148675.000000,142408.000000,150060.000000,162008.000000,173695.000000,180109.000000,218187.000000,209048.000000,204487.000000,193549.000000,175133.000000,163029.000000,161158.000000,149001.000000,157221.000000,168541.000000,180774.000000,186891.000000,218102.000000,209112.000000,205563.000000,194655.000000,176539.000000,162653.000000,159862.000000,146734.000000,155022.000000,166691.000000,177747.000000,185267.000000,223016.000000,212904.000000,209014.000000,197950.000000,180246.000000,165814.000000,165814.000000,163210.000000,150203.000000,158962.000000,171146.000000,183424.000000,189661.000000,225209.000000,216802.000000,214582.000000,204647.000000,187371.000000,167206.000000,168762.000000,156248.000000,165584.000000,179247.000000,192813.000000,199497.000000,226277.000000,217290.000000,214534.000000,204554.000000,186754.000000,114712.000000,127969.000000,123468.000000,133562.000000,146075.000000,160304.000000,169453.000000,163575.000000,156840.000000,154272.000000,146867.000000,134327.000000,12412.000000,13106.000000,12957.000000,12741.000000,12928.000000,12813.000000,13173.000000,13418.000000,13302.000000,13351.000000,13279.000000,13000.000000,59711.000000,64290.000000,65091.000000,69934.000000,75175.000000,81256.000000,67368.000000,69541.000000,69197.000000,69603.000000,69005.000000,67217.000000

In [25]:
# сохранение обработанного датасета по 8 показателям (с дополнительными регрессорами)
df_combined.to_excel("output data/Просуммированные по категориям с доп регрессорами.xlsx", index=False)